### ISSUE TITLE
图注问题

### ISSUE THREAD

**Issue by rainharp** [dustincys/hithesis#10]
你好，请问如何实现下图这样的图注呢?
![qq 20171228215411](https://user-images.githubusercontent.com/1862710/34412737-f9f88106-ec19-11e7-86fc-a1a2b3d28e36.jpg)

**Comment by dustincys** [comment]
这个问题很好，规范规定：

>  “子图图题可以在主图题之下显示”

**但没有给出具体格式要求**。依照窝工惯例，“没有给出格式”的意思应该就是“无论什么格式都不对”。总会有无数说法，无数看不惯。

以此图为例，有人要求a,b,c在同一行之内 或者 c 居中之类。原来我想，这种奇葩图题绝对不会有人用到，所以在示例中就没有添加这个形式。不过我会处理。

**Comment by dustincys** [comment]
原来我以为这种图题绝不会有人用到，我忽略了引用图、和不可分割子图的形式。实际上就是一个图片，图片内部含有文字(a)或(b)或(c)这种形式。这样才不得不将子图图题放到主图题之下。

这样我需要重新定义环境，估计要码很多东西。

**Comment by rainharp** [comment]
嗯嗯，因为有同学最近用a) b) c)合并一行图注的论文没有通过，学校说分图题要放在下面。但夏天毕业的一批同学学校又都没有提出这样的问题

**Comment by dustincys** [comment]
先给出一个临时的
[设置方法](https://github.com/dustincys/hithesis/commit/4844a04ceb76f32c0d6ca6600044848bec4454d1#diff-fcb936c911d1198c43e9521d6cef9f7aR170)

如果要彻底（优雅地？）解决这个问题，需要定义类似 \bisubcaptionbox[width][pos]{中文}[英文]格式的命令，可以交叉引用。后续有时间再添加吧。
