### ISSUE TITLE
威海本科毕业论文若干格式更新

### ISSUE THREAD

**Issue by LEON-REIN** [dustincys/hithesis#100]
# **描述bug类型**

- 校区（哈尔滨/威海/深圳？）：
  威海

- 学位（本/硕/博？）：
  本科

- 论文类型（毕业论文/开题/中期/博后/English Version？）：  
  毕业论文

- 证据（与规范不符/与word模板不符？）：  
  3.0.15版本生成与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

  网址：http://jwc.hitwh.edu.cn/bysj/list.htm
  中的`哈尔滨工业大学本科毕业设计（论文）相关资料下载`项目点击下载后压缩包内的`书写范例`

# **描述三个bug具体信息(hithesis 3.0.15版本)** 
1. 多了一个封面
窝工在word模板中第1页规定格式为：
![image](https://user-images.githubusercontent.com/35730051/122013354-accea100-cdf0-11eb-827c-2c8e2b91b344.png)
hithesis的格式中多出了如下一页：
![image](https://user-images.githubusercontent.com/35730051/122013444-c40d8e80-cdf0-11eb-962f-dca14c1fe673.png)

2. 学校logo不含威海
窝工在word模板中第一页的logo规定格式为：
![image](https://user-images.githubusercontent.com/35730051/122014110-6e85b180-cdf1-11eb-84c5-d695dddaf591.png)
hithesis的格式中对应页(第二页)的logo为：
![image](https://user-images.githubusercontent.com/35730051/122014240-8b21e980-cdf1-11eb-8730-16b1c2bd3582.png)

3. 诚信说明书的文字内容、字体、所在位置、目录中名称不相符
窝工在word模板中第8页的诚信声明书规定格式为：
![image](https://user-images.githubusercontent.com/35730051/122014959-40ed3800-cdf2-11eb-9187-021e1800997e.png)
hithesis的格式由`\authorization`命令生成的对应诚信说明为：
![image](https://user-images.githubusercontent.com/35730051/122015187-74c85d80-cdf2-11eb-92d3-1e08637835b1.png)
此外，word模板中诚信说明书的所在位置为：结论-->诚信声明书-->参考文献-->致谢；
hithesis中为：结论-->参考文献-->原创性声明-->致谢，且在目录中名字为“...原创性声明...”。

4. 一些杂项提议
    建议添加切换致谢部分字体（楷书或宋体）的选项，word模板只说正文要宋体，我也不知对致谢是否也如此要求。
    word模板中参考文献处中文引用的字体为宋体，hithesis生成的参考文献中中文条目为楷书，我也母鸡对不对，反正word模板中的参考文献奇怪地用了**全角标点**应该不对QwQ。

# 附言
本人在使用针对上述问题时做了如下调整：
1. thesis.tex 中，把第19行的campus选项改用harbin来替代weihai，来解决logo问题
 > 原代码：
 > \documentclass[fontset=windows,type=bachelor,campus=weihai]{hithesisbook}

2. hithesisbook.cfg(3.0.15 版本) 中修改以适配诚信说明书部分
    第341行起改为
  ```latex
 \newcommand{\hit@authorizationtext@bachelor}{%
 \kaishu
 本人呈交给哈尔滨工业大学的学位论文，除所列参考文献和世所公认的文献外，全部是本人毕业设计期间在导师指导下的研究成> 果。除文中已经标明引用的内容外，本论文不包含任何其他个人或集体已经发表或撰写过的研究成果。对本文的研究做出贡献的 个人和集体，均已在文中以明确方式标明。本人完全意识到本声明的法律结果由本人承担。
 
 若有不实之处，本人愿意承担相关法律责任。}
```
    第340行改为
  ```latex
   \newcommand{\hit@declarename@bachelor}{本科毕业论文（设计）诚信声明书}
  ```
    第286~287行改为
  ```latex
  \newcommand{\hit@authorsig}{\kaishu 作者签名：}
  \newcommand{\hit@teachersig}{\kaishu 导师签名：}
  ```

3. 修改 hithesisbook.cls (3.0.15 版本) 以适配诚信说明书部分
    第1530行起改为
  ```latex
  \def\hit@authorization@bachelor{%
    \ifhit@openright\cleardoublepage\else\clearpage\fi
    \hit@appendix@chapter*{\hit@declarename@bachelor}
    \hit@authorizationtext@bachelor
  \vspace{2\baselineskip}
  \par\hfill\hit@authorsig\hspace{6em}
  \vspace{1\baselineskip}
  \par\hfill\hit@teachersig\hspace{6em}
  \vspace{2\baselineskip}
  \par\hfill\hit@datefill
  }
  ```

**Comment by dustincys** [comment]
@LEON-REIN 
提交个PR 多好啊……
