### ISSUE TITLE
version 2021.4 hitbook/chinese docker 编译问题

### ISSUE THREAD

**Issue by Winds-Y** [dustincys/hithesis#101]
**2021.4版本docker 编译不通过**

- 哈尔滨（哈尔滨/威海/深圳？）：

- 硕（本/硕/博？）：

- 毕业论文（毕业论文/开题/中期/博后/English Version？）：

代码：
根目录抽取格式：
 docker run --rm -i  -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest latex hithesis.ins
chinese目录下编译hitbook：
docker run --rm -i  -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make thesis
结果：
![image](https://user-images.githubusercontent.com/32355578/123031047-419b5500-d416-11eb-9e86-79de1318c000.png)
报错：[21make: *** [Makefile:55: thesis.bbl] Broken pipe
结果说明：没有打开pdf，应该没有占用
tinytex-hithesis 的版本为两周前更新的最新版

**Comment by Winds-Y** [comment]
english目录下：
docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest make thesis
编译成功：
![image](https://user-images.githubusercontent.com/32355578/123031958-c5097600-d417-11eb-8e8c-1573713c3aca.png)

**Comment by dustincys** [comment]
make 不是tiny-tex的内部命令，所以make 会调用makefile，makefile 中的xelatex之类的命令都是外部命令。所以不要用make

**Comment by AtmaHou** [comment]
> make 不是tiny-tex的内部命令，所以make 会调用makefile，makefile 中的xelatex之类的命令都是外部命令。所以不要用make

我遇到了同样的问题，在docker里eng的可以编译成功，ch的不行，逐行编译也会失败，所以应该怎么编译呢？

**Comment by dustincys** [comment]
直接进入docker container内部，安装make等所有依赖，
然后更新docker image.
然后就可以了。

ch的不行应该是缺少什么包。
仔细看看缺少哪个包。

**Comment by dustincys** [comment]
已更新docker.
