### ISSUE TITLE
使用扫描授权页时，附录中的图可能会浮动到授权页之后

### ISSUE THREAD

**Issue by miRoox** [dustincys/hithesis#102]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨（应该是共性问题）

- 学位（本/硕/博？）：硕（应该是共性问题）

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：`\authorization` 与 `\authorization[saomiao.pdf]` 功能表现不一致

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：/

**描述bug具体信息（复现手段）** 

准备扫描页 `saomiao.pdf`。

`thesis.tex` 主要片段：

```tex
\documentclass[type=master]{hithesisbook}
\usepackage{hithesis}
\usepackage{lipsum}

% 中略

\begin{appendix}%附录
\input{back/appA.tex}
\end{appendix}
\authorization %授权
%\authorization[saomiao.pdf] %添加扫描页的命令，与上互斥

% 下略
```

`appA.tex`:

```tex
\chapter{带章节的附录}[Full Appendix]%
完整的附录内容，包含章节，公式，图表等

\section{附录节的内容}[Section in Appendix]

\lipsum[2-3]

\begin{figure}[htb]
\centering
\includegraphics[width = 0.4\textwidth]{golfer}
\caption{\xiaosi[0]打高尔夫球的人}
\end{figure}

\lipsum[4-5]
```

得到的图片位于正常的位置：

![hithesis-float-nosaomiao](https://user-images.githubusercontent.com/20090991/126971462-66f98a8c-633a-4478-a4a8-5de3d36e080a.png)

但如果使用扫描的授权页

```tex
%\authorization %授权
\authorization[saomiao.pdf] %添加扫描页的命令，与上互斥
```

图片会浮动到授权页的下一页：

![hithesis-float-saomiao](https://user-images.githubusercontent.com/20090991/126971319-dc08f353-b9bd-428e-b022-bfe811870207.png)

**Comment by Poofee** [comment]
使用PDF编辑软件手动替换啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yong-an Lu ***@***.***&gt;
发送时间: 2021年7月26日 18:06
收件人: dustincys/hithesis ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[dustincys/hithesis] 使用扫描授权页时，附录中的图可能会浮动到授权页之后 (#102)





 
描述bug类型
  
 
校区（哈尔滨/威海/深圳？）：哈尔滨（应该是共性问题）
 

 
学位（本/硕/博？）：硕（应该是共性问题）
 

 
论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文
 

 
证据（与规范不符/与word模板不符？）：\authorization 与 \authorization[saomiao.pdf] 功能表现不一致
 

 
证据所在网页（窝工规范或者word模板所在窝工官方网页）：/
 
 
描述bug具体信息（复现手段）
 
准备扫描页 saomiao.pdf。
 
thesis.tex 主要片段：
 \documentclass[type=master]{hithesisbook} \usepackage{hithesis} \usepackage{lipsum} % 中略 \begin{appendix}%附录 \input{back/appA.tex} \end{appendix} \authorization %授权 %\authorization[saomiao.pdf] %添加扫描页的命令，与上互斥 % 下略
 
appA.tex:
 \chapter{带章节的附录}[Full Appendix]% 完整的附录内容，包含章节，公式，图表等 \section{附录节的内容}[Section in Appendix] \lipsum[2-3] \begin{figure}[htb] \centering \includegraphics[width = 0.4\textwidth]{golfer} \caption{\xiaosi[0]打高尔夫球的人} \end{figure} \lipsum[4-5]
 
得到的图片位于正常的位置：
 

 
但如果使用扫描的授权页
 %\authorization %授权 \authorization[saomiao.pdf] %添加扫描页的命令，与上互斥
 
图片会浮动到授权页的下一页：
