### ISSUE TITLE
硕士开题模板图号、表号未带章节号的问题

### ISSUE THREAD

**Issue by ArtisticZhao** [dustincys/hithesis#105]
硕士开题模板图号、表号并非  1-1 这种带着章节号的，通篇从1开始标号。而且图号表号后存在一个冒号：

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题

- 证据（与规范不符/与word模板不符？）：窝工开题模板中确实没有规定图号 表号的形式

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

**描述bug具体信息** 

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：

hithesis的格式为

如图：
![image](https://user-images.githubusercontent.com/22850287/130308368-58acee04-5e59-4a29-b84e-ddf56cf2677f.png)

如码：
```
% 图码
\begin{figure}[h]
\centering
\includegraphics[width = 0.99\textwidth]{zu_arch}
\caption[zu_arch]{框图}
\label{zu_arch}
\end{figure}

% 表码
\begin{table}[htbp]
\bicaption[table1]{}{课题进度安排}
\vspace{0.5em}\centering\wuhao
\begin{tabular}{cc}
\toprule[1.5pt]
日期 & 项目\\
\midrule[1pt]
2021.09.01 \~{} 2021.09.07 & 方案设计与调研 \\
10 & 421.0 \\
20 & 640.2 \\
\bottomrule[1.5pt]
\end{tabular}
\end{table}

```
其他的问题：
1. 另外就是图片需要单独使用`\label{}`进行描述，否则将引用失败

2. 还有在正文引用图片表格时 需要
  ```
  \tablename{} \ref{table1}
  \figurename{} \ref{zu_arch}
  ```
  在前方加上描述符，否则只显示“如1所示”，但是我看论文模板中是直接引用的。

感谢作者提供好用的latex模板！

**Comment by dustincys** [comment]
@ArtisticZhao 

> 证据（与规范不符/与word模板不符？）：窝工开题模板中确实没有规定图号 表号的形式

所以应该就是1,2,3,4这种形式的

**Comment by ArtisticZhao** [comment]
@dustincys 
所以那个冒号有没有办法去掉呢？

**Comment by ArtisticZhao** [comment]
找到了去掉冒号的办法：
加入`\captiondelim{  }`
把默认的':' 替换成 ‘ ’

```
% 例子
\begin{figure}[h]
\centering
\captiondelim{  }
\includegraphics[width = 0.99\textwidth]{zu_arch}
\caption[zu_arch]{框图}
\label{zu_arch}
\end{figure}
```
