### ISSUE TITLE
开题报告的首段空两个字？

### ISSUE THREAD

**Issue by MayeZhang** [dustincys/hithesis#106]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：
- 哈尔滨

- 学位（本/硕/博？）：
- 硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：
- 开题

- 证据（与规范不符/与word模板不符？）：

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

**描述bug具体信息** 

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：

hithesis的格式为

如图：
![image](https://user-images.githubusercontent.com/42532687/131937814-4207979f-9127-4c15-80e0-9dc2383ba411.png)

如码：

**Comment by ArtisticZhao** [comment]
#89 这个提到过
![2021-09-03_21-16](https://user-images.githubusercontent.com/22850287/132011195-2b738f36-6493-4283-beb4-97f04ceaf205.png)
在`hithesisart.cls`的277行后 添加
```
subparagraph/afterindent=true, % 原有
punct=quanjiao, space=auto, autoindent=true  % 添加
```
