### ISSUE TITLE
硕士开题报告模板咨询

### ISSUE THREAD

**Issue by QUIlToT** [dustincys/hithesis#107]
作者你好！谢谢你的模板！
有个问题想向你咨询，hitart\reports\reports.tex中只有深圳博士开题报告、威海本科生开题和中期报告、本部本科生开题报告结构，请问有没有本部硕士开题报告的结构呢？谢谢。

**Comment by fanganpai** [comment]
report.tex里面type选master应该就可以吧

**Comment by QUIlToT** [comment]
> report.tex里面type选master应该就可以吧

哦哦，谢谢，还有个问题想问一下，排版出来发现条标题和行标题的行间距好像不对，跟本部要求的段前段后0.5行好像对不上，您知道是怎么回事吗？

**Comment by fanganpai** [comment]
我也觉得看上去不太对……但是规范里面确实说的是“**建议**段前0.5行，段后0.5行”，所以即使模板里没按这个来也是说得通的……还是等作者的说法吧
我用vspace大概模拟了一下，然而并不知道如何精确的控制0.5行。如果有什么更好的办法踢我一脚

**Comment by QUIlToT** [comment]
> 我也觉得看上去不太对……但是规范里面确实说的是“**建议**段前0.5行，段后0.5行”，所以即使模板里没按这个来也是说得通的……还是等作者的说法吧
> 我用vspace大概模拟了一下，然而并不知道如何精确的控制0.5行。如果有什么更好的办法踢我一脚

好嘞，谢谢您~
