### ISSUE TITLE
ctex 中报错

### ISSUE THREAD

**Issue by Feng-long** [dustincys/hithesis#12]
你好，
在windows环境下 ctex 中 运行生成论文这一步骤  xelatex main.tex 时候会出现下面的错误 

 
! LaTeX Error: Unknown option `AutoFakeBold=2' for package `fontspec'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.257 \ProcessOptions*

? H
The option `AutoFakeBold=2' was not declared in package `fontspec', perhaps you

misspelled its name. Try typing  <return>  to proceed.
?

**Comment by poofee** [comment]
更新你的ctex到最新版一般就没有问题

**Comment by Feng-long** [comment]
@poofee  我用的是ctex 2.9.2.164 包含完整版MiKTeX的 应该算是最新的稳定版本了

**Comment by poofee** [comment]
你去官网看一下啥时候发布的，2012年
CTeX Release Notes
v2.9.2.164 -- 2012.03.22
修正 WinEdt 中 CCT 菜单设置错误
修改 WinEdt 不使用 UTF-8 作为缺省编码
升级 WinEdt 7.0 20120321
升级 GSview 5.0
升级 Ghostscript 9.05
更新 SumatraPDF 2.0 r5987
更新 MiKTeX 2.9

不是说miktex不是最新的，而是库文件是旧的

**Comment by yunzqq** [comment]
能不能说一下具体怎么解决？

**Comment by yunzqq** [comment]
sorry, but xelatex.exe did not succeed.  生成不了pdf怎么解决

**Comment by yunzqq** [comment]
> 你好，
> 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误
> 
> ! LaTeX Error: Unknown option `AutoFakeBold=2' for package `fontspec'.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type H for immediate help.
> ...
> 
> l.257 \ProcessOptions*
> 
> ? H
> The option `AutoFakeBold=2' was not declared in package `fontspec', perhaps you
> 
> misspelled its name. Try typing to proceed.
>请问一下怎么结局的？ win10 CTEX也是最新的版本

**Comment by Poofee** [comment]
ctex过时了，卸载安装miktex或texlive



---原始邮件---
发件人: "George_Zhang"<notifications@github.com&gt;
发送时间: 2020年5月14日(周四) 下午5:11
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;;
主题: Re: [dustincys/hithesis] ctex 中报错 (#12)




  
你好，
 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误
 
! LaTeX Error: Unknown option AutoFakeBold=2' for package fontspec'.
 
See the LaTeX manual or LaTeX Companion for explanation.
 Type H for immediate help.
 ...
 
l.257 \ProcessOptions*
 
? H
 The option AutoFakeBold=2' was not declared in package fontspec', perhaps you
 
misspelled its name. Try typing to proceed.
 请问一下怎么结局的？ win10 CTEX也是最新的版本

**Comment by yunzqq** [comment]
> ctex过时了，卸载安装miktex或texlive
> […](#)
> ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:11 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) 你好， 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误 ! LaTeX Error: Unknown option AutoFakeBold=2' for package fontspec'. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.257 \ProcessOptions* ? H The option AutoFakeBold=2' was not declared in package fontspec', perhaps you misspelled its name. Try typing to proceed. 请问一下怎么结局的？ win10 CTEX也是最新的版本 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

是miktex啊   CTEX完整包带的啊

**Comment by Poofee** [comment]
对，卸载，去miktex官网下载最新版



---原始邮件---
发件人: "George_Zhang"<notifications@github.com&gt;
发送时间: 2020年5月14日(周四) 下午5:19
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;;
主题: Re: [dustincys/hithesis] ctex 中报错 (#12)




  
ctex过时了，卸载安装miktex或texlive
 …
 ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:11 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) 你好， 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误 ! LaTeX Error: Unknown option AutoFakeBold=2' for package fontspec'. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.257 \ProcessOptions* ? H The option AutoFakeBold=2' was not declared in package fontspec', perhaps you misspelled its name. Try typing to proceed. 请问一下怎么结局的？ win10 CTEX也是最新的版本 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是miktex啊   CTEX完整包带的啊

**Comment by yunzqq** [comment]
> 对，卸载，去miktex官网下载最新版
> […](#)
> ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:19 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) ctex过时了，卸载安装miktex或texlive … ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:11 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) 你好， 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误 ! LaTeX Error: Unknown option AutoFakeBold=2' for package fontspec'. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.257 \ProcessOptions* ? H The option AutoFakeBold=2' was not declared in package fontspec', perhaps you misspelled its name. Try typing to proceed. 请问一下怎么结局的？ win10 CTEX也是最新的版本 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 是miktex啊 CTEX完整包带的啊 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

OK

**Comment by yunzqq** [comment]
> 对，卸载，去miktex官网下载最新版
> […](#)
> ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:19 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) ctex过时了，卸载安装miktex或texlive … ---原始邮件--- 发件人: "George_Zhang"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 下午5:11 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Poofee"<poofee@qq.com&gt;; 主题: Re: [dustincys/hithesis] ctex 中报错 (#12) 你好， 在windows环境下 ctex 中 运行生成论文这一步骤 xelatex main.tex 时候会出现下面的错误 ! LaTeX Error: Unknown option AutoFakeBold=2' for package fontspec'. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.257 \ProcessOptions* ? H The option AutoFakeBold=2' was not declared in package fontspec', perhaps you misspelled its name. Try typing to proceed. 请问一下怎么结局的？ win10 CTEX也是最新的版本 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 是miktex啊 CTEX完整包带的啊 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/12210635/81918670-60bb9680-9609-11ea-8fa8-00b197c6e0fb.png)
新的问题 哥们

**Comment by Poofee** [comment]
人家不是让你更新宏包吗

**Comment by yunzqq** [comment]
![image](https://user-images.githubusercontent.com/12210635/81919979-1b986400-960b-11ea-96b0-2113030183c5.png)
一样啊 老哥

**Comment by Poofee** [comment]
不是让你把ctex卸载吗 它调用的还是d盘的miktex

**Comment by yunzqq** [comment]
> 不是让你把ctex卸载吗 它调用的还是d盘的miktex

我是跟新了MikTex，原来的MikTeX被改成其他名字了，新的直接用了MikTex名字，这样环境变量就不用改了，调用的应该是最新的MikTex。    可以加一下QQ私聊么？

**Comment by Poofee** [comment]
1225949995
