### ISSUE TITLE
上传overleaf编译超时

### ISSUE THREAD

**Issue by taojingcong** [dustincys/hithesis#122]
- 深圳：

- 硕：

- 毕业论文：

上传overleaf编译超时，能否缩短一下编译时间

**Comment by syvshc** [comment]
将 `latexmkrc` 文件中的

```
$preview_continuous_mode = 0;
```

改为

```
$preview_continuous_mode = 0;
```

即可, 这是用于本地编译自动检测更改的选项, 在 overleaf 中会检测不到编译结束从而超时.
