### ISSUE TITLE
v3.0.19中引用文献标注出现加黑bug

### ISSUE THREAD

**Issue by RunanWang** [dustincys/hithesis#125]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：窝工规范

**描述bug具体信息** 

窝工在（word模板中）第“2.6  引用文献标注”规定格式为：

如图：

![image](https://user-images.githubusercontent.com/33189397/167652761-3fd46886-6452-40ac-9480-0bfa6ad32351.png)

![image](https://user-images.githubusercontent.com/33189397/167654011-faca7214-2749-4747-9378-169b166f28e2.png)

hithesis的格式为

![image](https://user-images.githubusercontent.com/33189397/167653152-a8dc8929-c1c1-4d69-9efb-b0152d25ea1d.png)

![image](https://user-images.githubusercontent.com/33189397/167653898-25012f47-e406-434b-9506-6462834f0f07.png)

上两图对比可得，hithesis的引用文献标注似乎被加黑了。我在Word中复现了这个问题：

![image](https://user-images.githubusercontent.com/33189397/167653540-eb9a087b-5f1c-4a1a-9068-f36c2ce7d96a.png)

如图，前一种为规范，后一种为hithesis的格式。

## Bug 原因推测

Log中有如下报错：

LaTeX Font Warning: Font shape `OMS/TeXGyreTermesX(0)/m/n' undefined
(Font)              using `OMS/cmsy/m/n' instead on input line 7.

结合5月5日更新中% \changes{v3.0.19}{2022/05/05}{将 TG Termes 字体替换为 TG TermesX 字体，与 \pkg{newtxmath} 宏包更适配，删除 \option{Scale} 选项。}

我怀疑是这里出现了问题。

遂尝试将其回滚成TG Termes字体，即cls文件中TeXGyreTermesX更改成TeXGyreTermes。

\setmainfont{TeXGyreTermes}[
  UprightFont = *-Regular ,
  BoldFont = *-Bold ,
  ItalicFont = *-Italic ,
  BoldItalicFont = *-BoldItalic ,
  Extension = .otf ,
  ]

问题得到暂时的解决。（或者直接使用v3.0.18？）

**Comment by syvshc** [comment]
神奇的问题, 我看看能不能揪到原因……

**Comment by syvshc** [comment]
报出的这个警告应该是某些数学字体的警告, 如果可以的话请检查一下在 `TeX Gyre TermesX` 设置下有哪些数学字体异常. 另外参考文献这个我没有在一般的文件中复现出来, 它似乎只存在于 `hithesis`...
