### ISSUE TITLE
Ubuntu16.04下使用问题

### ISSUE THREAD

**Issue by wd-hub** [dustincys/hithesis#14]
你好，
我在ubuntu16.04下按照bilibili上的使用简介运行程序，在'make doc'时出现错误 
!LaTeX Error: File `ctex.sty' not found.
运行'make thesis'则出现错误
! LaTeX Error: File `ctexbook.cls' not found.
我之前apt-get install texlive安装的是非完整版，运行英文模板一切正常，这个问题貌似是缺少ctex相关文件，请问是这样吗？应该怎么安装相关组件?
谢谢！

**Comment by dustincys** [comment]
@wd-hub

你好，

你说的对，缺少ctex 包。安装方法我不是特别清楚，一般情况下，安装
texlive-full 之类的完全数据包。或者miktex。
到ctan网站上查一查就知道了。

或到谷歌上百度一下……
