### ISSUE TITLE
在论文的封面加了水印

### ISSUE THREAD

**Issue by hitspring2015** [dustincys/hithesis#15]
请问怎么把论文的封面上面的水印去掉，嗨 thesis

**Comment by dustincys** [comment]
@hitspring2015 水印不是随便删除的，因为CTEX处理中文字体（特别是Windows的经典宋体）时候的经典bug: “首次出现的字体且该字体不是粗体，则后续字体无法使用粗体”，如果去除水印，则封面页无法正确现实windows的经典粗体。

如果实在想去除也简单，设置fontset=siyuan 使用思源字体，没有上面的CTEX bug。所以模板的逻辑是如果使用思源字体，则没有水印。

**Comment by poofee** [comment]
怎么看到的

**Comment by hitspring2015** [comment]
那我可以修改那个水印吗？让水印变成别的显示 @dustincys

**Comment by hitspring2015** [comment]
谢谢您 @dustincys 已经修改完了，在dtx 和 cfg文件中搜索到嗨thesis，把它们替换为自己想要的相应的字即可修改水印内容！
