### ISSUE TITLE
表格想去掉英文标题

### ISSUE THREAD

**Issue by hitspring2015** [dustincys/hithesis#16]
\bicaption[table1]{}{符合研究生院绘图规范的表格}{Table$\!$}{Table in agreement of the standard from graduate school}
% \vspace{0.5em}\centering\wuhao
% \begin{tabular}{ccccc}
% \toprule[1.5pt]
% $D$(in) & $P_u$(lbs) & $u_u$(in) & $\beta$ & $G_f$(psi.in)\\
% \midrule[1pt]
%  5 & 269.8 & 0.000674 & 1.79 & 0.04089\\
% 10 & 421.0 & 0.001035 & 3.59 & 0.04089\\
% 20 & 640.2 & 0.001565 & 7.18 & 0.04089\\
% \bottomrule[1.5pt]
% \end{tabular}
% \end{table}

请问上面怎么去掉英文标题？

**Comment by dustincys** [comment]
参见硕士论文的表示示例

**Comment by hitspring2015** [comment]
原来我用sublime text编有一个文件没加进去，一直有错，用另外的编辑器就可以了，现在解决了！
