### ISSUE TITLE
Mac如何使用此模版？

### ISSUE THREAD

**Issue by HumanGenerator** [dustincys/hithesis#17]
在main.tex中把fontset设为空，排版时报错
./hithesis.cls:116: Undefined control sequence.
l.116 ...ith\MessageBreak \DeclareUnicodeCharacter
                                                     \errhelp f\let \def \Me

**Comment by dustincys** [comment]
推荐MAC排版方法：

1. 安装windows中易字体（即常见宋、黑、楷，最好win7+）到Mac系统中。
2. 设置fontset=windowsnew （如果是win7- 使用windowold)。

理由是大家都用中易字体。

**Comment by poofee** [comment]
我装完mactex后，编译没有任何问题啊

**Comment by philleer** [comment]
Mac系统里面的字体如何对应，例如下面的字体在Mac对应的都是什么名字呢
```
\setCJKmainfont [ BoldFont = SimHei , ItalicFont = KaiTi ] { SourceHanSerifCN-Regular }
\setCJKsansfont [ BoldFont = { *~Bold } ] { Microsoft~YaHei }
\setCJKmonofont { FangSong }
\setCJKfamilyfont { zhkai } { KaiTi }
\setCJKfamilyfont { zhfs }  { FangSong }
\setCJKfamilyfont { zhsong }  { SourceHanSerifCN-Regular }
\setCJKfamilyfont { zhhei }   { SimHei }
\setCJKfamilyfont { zhli }    { LiSu }
\setCJKfamilyfont { zhyou }   { YouYuan }
\setCJKfamilyfont { zhyahei } [ BoldFont = { *~Bold } ] { Microsoft~YaHei }
```

**Comment by dustincys** [comment]
hi rhiller,

Mac推荐安装windows字体。main.tex中有详细说明。

**Comment by philleer** [comment]
好的，谢谢回复。我在提问之后又仔细阅读了文档和各个提问中的回答，安装了相应的字体，修改了main.texdocumentclass的字体设置，现在已经可以用了，后来我应该已经把提问删除了，可能没操作成功，多有打扰敬请谅解。
ps. 我在Mac Majove上安装的是适用win7的中易字体，fontset=windowsold之后才可以使用，原来楼上的解决方案里说明的win7+是不包含win7的。
