### ISSUE TITLE
为什么不让加QQ群啊。。

### ISSUE THREAD

**Issue by Perfeee** [dustincys/hithesis#25]
在Windows7下面使用texlive和texStudio编译，出现以下错误信息，怎么解决啊？

fontspec error: "font-not-found" The font "SourceHanSerifCN-Regular" cannot be found. For immediate help type H <return>. }

**Comment by Perfeee** [comment]
谢谢回复啊,不过我把fontset的三种选项都试了，分别都有不一样的not found问题。。

**Comment by dustincys** [comment]
QQ群一直是开放的

**Comment by dustincys** [comment]
如果没有后续问题，关闭issue了

**Comment by Perfeee** [comment]
qq群回答问题，不通过啊。。。答案hithesis是错误的。。

**Comment by dustincys** [comment]
不可能……

**Comment by dustincys** [comment]
名称全小写，不可能不对
