### ISSUE TITLE
有没有生成好的pdf文档

### ISSUE THREAD

**Issue by zymprogramer** [dustincys/hithesis#28]
我下了压缩包后，按readme生成了cls等文档，但是生成论文一直报错，生成说明文档也报错，有没有生成好的说明文档可以用？

**Comment by poofee** [comment]
哪个文档？

**Comment by zymprogramer** [comment]
不用了，我生成文档成功了，就是hithesis.pdf这个文档，但是论文还是生成不成功，我用miktex和tex live都不行。我在windows系统中，直接在文档目录下按说明文档中xelatex main.tex 。。。生成，但是一直不成功

**Comment by PanZhichen** [comment]
重装下texlive2018版本，我以前的版本也是不行，升级下好了

**Comment by zymprogramer** [comment]
问题最终解决了，我安装了texlive 2018，安装了缺失的包以后，还是会报错，后来我又安装了一些没有明确要求的包（搜索了cjk，感觉能用的上的都安装了），变异成功。建议安装时直接将所有包都装好
