### ISSUE TITLE
目前遇到的几个小问题

### ISSUE THREAD

**Issue by ppoffice** [dustincys/hithesis#3]
感谢作者无私地奉献让我们用上了这样完善的模板！以下是我在使用过程中遇到的一些问题，望作者能够参考：

- [x] 表格内容行间距较小
- [x] 图片和表格浮动体上下间距较大
- [ ] 当参考文献为中文，且作者数量较多时，省略显示的是“et al”而不是“等”

**Comment by dustincys** [comment]
感谢反馈～，我会尽快调整

**Comment by dustincys** [comment]
- [x] 表格内容行间距较小
已经修改好，如果自己要调整表格中的字体，如从五号变为小五时，用\wuhao[1.667] 或\xiaowu[1.667]，使间距为常见的行距。（这个间距不在规范中要求）
- [x] 图片和表格浮动体上下间距较大
图片和表格的浮动距离默认为前后空一行（约20bp）(这个间距也不在规范中要求)
- [x] 当参考文献为中文，且作者数量较多时，省略显示的是“et al”而不是“等”
bib文件中额外添加一项language={zh}即可

**Comment by ppoffice** [comment]
感谢！
