### ISSUE TITLE
要写英文版本的论文，怎么方便地改字体

### ISSUE THREAD

**Issue by zymprogramer** [dustincys/hithesis#31]
我需要写英文版的论文，像章节标题需要用新罗马加粗，而且chaper 后要回车，还有图片标题只需要英文的，怎样可以简单的改一下.cls 和.cfg文件达到要求

**Comment by guangqi1223** [comment]
请问有什么进展吗。。

**Comment by zymprogramer** [comment]
我自己在.cls和.cfg里手动改的，有一些格式没有严格按照学校要求来，最后也通过了

**Comment by guangqi1223** [comment]
能给我发一份你改的用一下吗，我感觉看懂这个程序好难啊。。主要也不太懂那些命令，我觉得主要改的是目录，我只能直接在.toc和.toe文件里改，复制出来一份每次用，还行。章节标题用 pdf expert 改的，感觉很麻烦。。。

**Comment by dustincys** [comment]
除非有明确的规范规定才能改，要不然会有很有用户提出反对
