### ISSUE TITLE
算法只有AlgoBiCaption双语的么

### ISSUE THREAD

**Issue by lgz583** [dustincys/hithesis#36]
算法只有AlgoBiCaption双语的么，想只加入中文

**Comment by dustincys** [comment]
@lgz583 hi,

\begin{algorithm}[!t]
\small
\SetAlgoLined
\SetKwInput{subfunction}{Sub-Function}
\SetKwInput{function}{Function}
\SetKwInput{Input}{Input}
\SetKwInput{Output}{Output}
\Input{All the subclonal frequency order vector $\theVector{\phi}$ and
corresponding data index vector $\theVector{\varkappa}$ for all the sample.}
\Output{Time order vector $\theVector{t}$ and the negative set
$\{\theSet{Q}_j\}_{j=1}^J$ for all data.}
\function{CS2T($\{(\theVector{\varkappa}_z, \theVector{\phi}_z)\}_{z=1}^Z$)}
\Begin{
\Return $\theVector{t}$, $\{\theSet{Q}_j\}_{j=1}^J$\;
}
\caption{交叉规则到层次拓扑规则的变换}
\label{algoCrossing}
\end{algorithm}
