### ISSUE TITLE
如何去掉页眉？

### ISSUE THREAD

**Issue by Mddct** [dustincys/hithesis#38]
如何去掉页面，有全局的变量吗？

**Comment by Poofee** [comment]
去查找cls文件删掉相关的地方。大概是这一部分，
\fancypagestyle{hit@headings}{%
  \fancyhf{}
  \ifhit@doctor
  \fancyhead[CO]{\songti\xiaowu[0]\leftmark}
  \fancyhead[CE]{\songti\xiaowu[0]\hit@cschoolname\hit@cdegree\hit@cthesisname}%
  \else
  \ifhit@master
  \fancyhead[C]{\songti\xiaowu[0]\hit@cschoolname\hit@cdegree\hit@cthesisname}
  \fi
  \fi
  \ifhit@bachelor
  \fancyhead[C]{\songti\xiaowu[0]\hit@cschoolname\hit@bachelor@cxuewei\hit@bachelor@cthesisname}%
  \fancyfoot[C]{\xiaowu\if@mainmatter\ifhit@bsmainpagenumberline-~\thepage~-\else\thepage\fi\else\ifhit@bsfrontpagenumberline-~\thepage~-\else\thepage\fi\fi}
  \ifhit@bsheadrule
  \renewcommand{\headrule}{
  \vskip 1.190132pt
  \hrule\@height2.276208pt\@width\headwidth
  \vskip 0.75pt
  \hrule\@height.75pt\@width\headwidth
  }
  \else
  \renewcommand{\headrulewidth}{0pt}
  \fi
  \else
  \fancyfoot[C]{\xiaowu-~\thepage~-}
  \renewcommand{\headrule}{
  \vskip 1.190132pt
  \hrule\@height2.276208pt\@width\headwidth
  \vskip 0.75pt
  \hrule\@height.75pt\@width\headwidth
  }
  \fi

把不想要的地方注释掉

**Comment by Mddct** [comment]
ok 可以了 。注视掉 fancyhead 那行就可以了
