### ISSUE TITLE
如何改变chapter的显示格式

### ISSUE THREAD

**Issue by Mddct** [dustincys/hithesis#39]
比如 ： 第一章 xxxxx  修改为 1. xxx

**Comment by dustincys** [comment]
@Mddct hi, why?

**Comment by Regulust** [comment]
@Mddct 1.xxx应该是section节标题的格式，不是章标题的格式要求😂

**Comment by dustincys** [comment]
章节格式1.xxx不符合规范要求，所以这不是issue。如果没有问题我就关闭了
