### ISSUE TITLE
小小小问题

### ISSUE THREAD

**Issue by muyeby** [dustincys/hithesis#4]
首先感谢作者为大家提供了非常方便的latex模板（不知道窝工要到哪年才会提供官方的latex模板 =_=
然后说下我遇到的小问题：
1. main.tex的本科书序有几个include的文件位置好像写错了...(强迫症
2. authorization里“学位论文原创性声明”中的作者签名后有两个冒号，简单看了下，似乎是逻辑问题？
总之，希望作者有时间可以修复下吧：）

**Comment by muyeby** [comment]
另，请教一个问题：
为什么英文的参考文献里会多出一个“//”啊？两张截图分别在：http://7xigyc.com1.z0.glb.clouddn.com/reference.png
http://7xigyc.com1.z0.glb.clouddn.com/refpaper.png

**Comment by poofee** [comment]
作者签名的冒号不是已经改过来了吗？
那就是参考文献的格式，你搜一搜就知道了

**Comment by dustincys** [comment]
hi muyeby,

不用谢，如poofee所说，要用最新的模板，尤其是本科生模板，纠正了一些错误，如页眉页码格式，现在的authorization与教务处给出的范例一致。

不过本科生一定要额外注意[这个规范中的矛盾之处](http://yanshuo.name/cn/2017/06/hithesissiyuan/)。

**Comment by muyeby** [comment]
好的
