### ISSUE TITLE
编译时出现指令重定义问题

### ISSUE THREAD

**Issue by philleer** [dustincys/hithesis#40]
```
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "main.tex"
Startup Folder: E:\MyFiles_CV\paper\hithesis_v1

This is XeTeX, Version 3.14159265-2.6-0.999991 (MiKTeX 2.9.7200 64-bit)
entering extended mode
(main.tex
LaTeX2e <2019-10-01>
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/hithesis\hithesis.cls"
Document Class: hithesis 2018/12/05 2.0.6 Harbin Institute of Technology Thesis
 Template
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ifthen.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/oberdiek\kvoptions.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/graphics\keyval.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\ltxcmds.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\kvsetkeys.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\infwarerr.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\etexcmds.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\ifluatex.sty"))))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexbook.cls"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\expl3.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\expl3-code.tex"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\l3deprecation.def"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3backend\l3backend-xdvipdfmx.de
f"))
Document Class: ctexbook 2019/05/29 v2.4.16 Chinese adapter for class book (CTE
X)
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/xparse\xparse.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/l3keys2e\l3keys2e.sty
") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexhook.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexpatch.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fix-cm.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ts1enc.def"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ms\everysel.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/config\ctexopts.cfg")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\book.cls"
Document Class: book 2019/08/27 v1.4j Standard LaTeX document class
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\bk12.clo"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/engine\ctex-engine-xetex.de
f" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/xtemplate\xtemplate.s
ty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec-xetex.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fontenc.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\tuenc.def"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec.cfg")))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.cfg"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJKfntef.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ulem\ulem.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/cjk\CJKfntef.sty")))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/zhnumber\zhnumber.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/zhnumber\zhnumber-utf8.cfg"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/scheme\ctex-scheme-plain-bo
ok.def") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctex-cs4size.clo")

("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/fontset\ctex-fontset-window
snew.def")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/config\ctex.cfg
") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/etoolbox\etoolbox.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/ifxetex\ifxetex.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amstext.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsgen.sty"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsbsy.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsopn.sty"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/newtx\newtxtext.sty"
`newtxtext' v1.531, 2018/03/27 Text macros taking advantage of TeX-Gyre Termes 
fonts (msharpe)
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontaxes\fontaxes.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/xkeyval\xkeyval.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/xkeyval\xkeyval.tex"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/xkeyval\xkvutils.tex")))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fontenc.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\t1enc.def")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/lm\t1lmr.fd"))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\textcomp.sty"
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ts1enc.def")))
("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/newtx\newtxmath.sty"
`newtxmath' v1.605, 2019/10/23 Math macros based originally on txfonts (msharpe
) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/oberdiek\centernot.sty")
("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/binhex\binhex.tex")

! LaTeX Error: Command `\lvert' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.783 ...thopen}  {symbols}{106}{largesymbols}{12}
                                                  
? 
```
Windows 7使用CTEX MiKTeX编译模板出现定义冲突问题，应该怎么解决？MikTeX, WinEdt这些都更到最新版本了，这个问题一直过不去……
@dustincys

**Comment by dustincys** [comment]
Readme 中说明用texlive&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: philleer <notifications@github.com&gt;
发送时间: 2019年10月31日 00:18
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Dustin <yanshuochu@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 编译时出现指令重定义问题 (#40)



Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "main.tex" Startup Folder: E:\MyFiles_CV\paper\hithesis_v1 This is XeTeX, Version 3.14159265-2.6-0.999991 (MiKTeX 2.9.7200 64-bit) entering extended mode (main.tex LaTeX2e <2019-10-01&gt; ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/hithesis\hithesis.cls" Document Class: hithesis 2018/12/05 2.0.6 Harbin Institute of Technology Thesis  Template ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ifthen.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/oberdiek\kvoptions.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/graphics\keyval.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\ltxcmds.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\kvsetkeys.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\infwarerr.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\etexcmds.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/oberdiek\ifluatex.sty")))) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexbook.cls" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\expl3.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\expl3-code.tex" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3kernel\l3deprecation.def")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3backend\l3backend-xdvipdfmx.de f")) Document Class: ctexbook 2019/05/29 v2.4.16 Chinese adapter for class book (CTE X) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/xparse\xparse.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/l3keys2e\l3keys2e.sty ") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexhook.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctexpatch.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fix-cm.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ts1enc.def")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ms\everysel.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/config\ctexopts.cfg") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\book.cls" Document Class: book 2019/08/27 v1.4j Standard LaTeX document class ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\bk12.clo")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/engine\ctex-engine-xetex.de f" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/l3packages/xtemplate\xtemplate.s ty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec-xetex.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fontenc.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\tuenc.def")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontspec\fontspec.cfg"))) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.cfg")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJKfntef.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ulem\ulem.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/cjk\CJKfntef.sty"))) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/zhnumber\zhnumber.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/zhnumber\zhnumber-utf8.cfg")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/scheme\ctex-scheme-plain-bo ok.def") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex\ctex-cs4size.clo") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/fontset\ctex-fontset-window snew.def")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/ctex/config\ctex.cfg ") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/etoolbox\etoolbox.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/ifxetex\ifxetex.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsmath.sty" For additional information on amsmath, use the `?' option. ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amstext.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsgen.sty")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsbsy.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/amsmath\amsopn.sty")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/newtx\newtxtext.sty" `newtxtext' v1.531, 2018/03/27 Text macros taking advantage of TeX-Gyre Termes  fonts (msharpe) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/fontaxes\fontaxes.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/xkeyval\xkeyval.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/xkeyval\xkeyval.tex" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/xkeyval\xkvutils.tex"))) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\fontenc.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\t1enc.def") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/lm\t1lmr.fd")) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\textcomp.sty" ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/base\ts1enc.def"))) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/newtx\newtxmath.sty" `newtxmath' v1.605, 2019/10/23 Math macros based originally on txfonts (msharpe ) ("D:\Program Files (x86)\CTEX\MiKTeX\tex/latex/oberdiek\centernot.sty") ("D:\Program Files (x86)\CTEX\MiKTeX\tex/generic/binhex\binhex.tex") ! LaTeX Error: Command `\lvert' already defined. See the LaTeX manual or LaTeX Companion for explanation. Type  H <return&gt;  for immediate help.  ...                                                                                                  l.783 ...thopen}  {symbols}{106}{largesymbols}{12}                                                    ?   
Windows 7使用CTEX MiKTeX编译模板出现定义冲突问题，应该怎么解决？MikTeX, WinEdt这些都更到最新版本了，这个问题一直过不去……
 @dustincys

**Comment by philleer** [comment]
使用了CTEX里面的texlive也没能通过编译，还是下载安装了TeXLive2019编译通过，现在可以用了，多谢 @dustincys
