### ISSUE TITLE
关于摘要、目录、结论等页面的页眉问题

### ISSUE THREAD

**Issue by heany** [dustincys/hithesis#42]
![80471575704975_ pic](https://user-images.githubusercontent.com/28182428/70371362-e9246580-190c-11ea-9809-58ea26070bda.jpg)
![772D60E2535303CAA7C508ED8E2F882A](https://user-images.githubusercontent.com/28182428/70371365-f17ca080-190c-11ea-9ab1-f30f2f35e49b.jpg)
![784656058887A71D44BAB8DA6FD32450](https://user-images.githubusercontent.com/28182428/70371366-f6d9eb00-190c-11ea-9689-626d5f06f1e3.jpg)

硕士毕业论文模版里面**摘要**、**目录**、**结论**，**每一章的首页处**、**攻读硕士学位期间发表的论文页面**等的页眉都不是“**哈尔滨工业大学工学硕士学位论文**”，而是对应的页面的标题，请问如何修改，才能跟学位论文模版上的页眉一致？

**Comment by dustincys** [comment]
更具　[1.1哈尔滨工业大学（深圳）硕士学位论文格式要求及审查要点2019年6月.pdf](http://due.hitsz.edu.cn/info/1211/1859.htm) 首页说明：

> 说明:此《硕士学位论文格式要求及审查要点》根据《哈工大研究生学位论
文撰写规范》编写制定,重点考虑往届学生易出错的地方,仅供我校区研究生撰
写学位论文时参考使用。**如有遗漏之处或与《撰写规范》不一致之处,以《撰写
规范》为准**。

所以这个要求一律以规范为准。
