### ISSUE TITLE
编译不成功问题

### ISSUE THREAD

**Issue by zhuyeyiyi** [dustincys/hithesis#44]
环境：Win 10, 软件：Winedit 10.3，MiKtex 2.9.
两处错误：
（1）LaTeX Error: Command \Bbbk already defined.
（2）LaTeX Error: File wct5 not found
解决：
（1）猜测包冲突，重复定义引起。可参考[链接](https://pctex.com/kb/86.html)。在模板文件hitthesis.cls中202行引用了Package{amssymb}与MTP2 fonts冲突引起。注释掉即可编译 %%\RequirePackage{amssymb}。
（2）作者的donate图片wct5被吃掉了，注释掉introduction.tex文件里面\section{关于捐助} 即可。有心的hiter可到github扫描donate.

附：如果提示某些包版本过低，可到 MiKtex Console updates 即可。高龄不毕业博士赶上疫情也是“问苍天，无语凝噎”。

**Comment by dustincys** [comment]
@zhuyeyiyi 
试一试读一下readme中抽取格式的方法。应该是没有抽取格式，使用软件自带的hithesis编译导致的，自带的版本比较旧。

虽“吾已不再是高龄不毕业老博士”，附赠一偈：

> 莫说佛前打坐，千蹭万磨，见几个摘来长生果？　　
哪堪青灯昏焰，暗云霜雨，几载苦读子云诗曰，
消尽青葱年华，颠倒岁月，怎知非寻一梦南柯！

**Comment by zhuyeyiyi** [comment]
哈哈，没有读Readme的习惯。 大家编译之前抽取格式就行 lualatex hithesis.ins。此处附上题主膝盖。

>哪管他青灯古佛误华年，待他日江湖相逢，必当把酒言欢！
