### ISSUE TITLE
缺少 `hitlogo.eps` 与 `bthesistitle.eps`

### ISSUE THREAD

**Issue by WangYihang** [dustincys/hithesis#48]
## 问题描述
由于缺少文件（`hitlogo.eps`、`bthesistitle.eps`），导致本科生毕业设计标题中没有学校 Logo。

## 期望结果

![image](https://user-images.githubusercontent.com/16917636/77632851-8a512d80-6f89-11ea-814e-bbc1e4b30f31.png)

## 现结果

![image](https://user-images.githubusercontent.com/16917636/77633037-d308e680-6f89-11ea-85d0-b85c26bb6bb9.png)

## 原因分析
这两个文件似乎是被不小心添加进入了 `.gitignore`，导致编译输出 PDF 中没有学校 Logo。

## 解决方案（用户）
ctan 的 [hithesis](https://ctan.math.illinois.edu/macros/latex/contrib/hithesis/figures/) 仓库中是正常的，可以从 ctag 中下载这两个文件并放置于 figures 文件夹中，重新编译项目即可。

## 解决方案（开发者）
取消 `.gitignore` 中对上述两个文件的注释

**Comment by dustincys** [comment]
图标已经矢量化放在dtx中，按照readme说明，先抽取格式应该就会生成图片



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王一航 <notifications@github.com&gt;
发送时间: 2020年3月26日 04:48
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 缺少 `hitlogo.eps` 与 `bthesistitle.eps` (#48)





 
问题描述
 
由于缺少文件（hitlogo.eps、bthesistitle.eps），导致本科生毕业设计标题中没有学校 Logo。
 
期望结果
 

 
现结果
 

 
原因分析
 
这两个文件似乎是被不小心添加进入了 .gitignore，导致编译输出 PDF 中没有学校 Logo。
 
解决方案（用户）
 
ctan 的 hithesis 仓库中是正常的，可以从 ctag 中下载这两个文件并放置于 figures 文件夹中，重新编译项目即可。
 
解决方案（开发者）
 
取消 .gitignore 中对上述两个文件的注释

**Comment by WangYihang** [comment]
@dustincys 原来如此！多谢大佬相助！:D

**Comment by WangYihang** [comment]
官方解决方案：
> https://github.com/dustincys/hithesis#%E6%A8%A1%E6%9D%BF%E7%9A%84%E7%BC%96%E8%AF%91%E6%96%B9%E6%B3%95
