### ISSUE TITLE
[BUG] 当 `campus=weihai` 的时候 `titlepage` 中 logo 误引用为 `shenzhencampus`

### ISSUE THREAD

**Issue by WangYihang** [dustincys/hithesis#49]
当 `campus=weihai` 的时候 `titlepage` 中 logo 误引用为 `\kaishu\yihao\hit@weihaicampus`。

> https://github.com/dustincys/hithesis/blob/master/hithesis.dtx#L2431
```tex
\ifhit@weihai%
\centering{\includegraphics[width=6.2cm]{hitlogo}~~\raisebox{0.2em}{\kaishu\yihao\hit@shenzhencampus}}
```
应该为
```tex
\ifhit@weihai%
\centering{\includegraphics[width=6.2cm]{hitlogo}~~\raisebox{0.2em}{\kaishu\yihao\hit@weihaicampus}}
```

**Comment by specialpointcentral** [comment]
按照威海的样式，`titlepage`后面是不应该加上`(威海)`的，应该是和本部一样的封面

**Comment by WangYihang** [comment]
> 按照威海的样式，`titlepage`后面是不应该加上`(威海)`的，应该是和本部一样的封面

@specialpointcentral 哦哦哦，多谢指正！但是目前的情况是现在 titlepage 后面加的是`（深圳）`，应该修正成这样吧：

> https://github.com/dustincys/hithesis/blob/master/hithesis.dtx#L2430-L2431
```tex
  \ifhit@weihai%
  \centering{\includegraphics[width=6.2cm]{hitlogo}
```

**Comment by specialpointcentral** [comment]
@WangYihang 问题看起来修复了，可以close #49 了

**Comment by dustincys** [comment]
威海校区和本部一样？，威海小伙伴都吧campus 设置harbin？...

**Comment by WangYihang** [comment]
> 威海校区和本部一样？，威海小伙伴都吧campus 设置harbin？...

@specialpointcentral 不知道除了封面还有没有别的不一样，如果完全一样的话或许是可以直接设置成 `harbin`？

**Comment by dustincys** [comment]
已修改
