### ISSUE TITLE
在ubuntu下编译出现错误好像是字体的问题

### ISSUE THREAD

**Issue by langsunny** [dustincys/hithesis#5]
首先感谢作者的分享！
我在ubuntu下编译出现如下提示
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "SourceHanSerifCN-Regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.79   }
        
? h
|'''''''''''''''''''''''''''''''''''''''''''''''
应该是找不到相关字体。
请问如何解决呢？都需要那些字体？，或者可以出个集成字体的版本的谢谢！

**Comment by poofee** [comment]
你装一个字体不就完了

**Comment by langsunny** [comment]
感觉需要添加字体，更改ctex-fontset-siyuan.def此文件，单改了几次没成功。

**Comment by dustincys** [comment]
hi langsunny,

其实Linux如何安装字体不在模板的范围之内。

谷歌、百度上一堆教程，这里不必重复啦。

安装好中易字体或者思源字体之后（提倡正版），在主文件中设置fontset就好。
