### ISSUE TITLE
无法引用bib中的misc类，如何引用url？

### ISSUE THREAD

**Issue by ycli0536** [dustincys/hithesis#52]
win10系统，所用编译命令封装在一个 **build.bat** 批处理文件中。

```
lualatex hithesis.ins



xelatex main.tex

bibtex main

xelatex main.tex

xelatex main.tex

splitindex main -s hithesis.ist

xelatex main.tex
```

面对bib中有misc类的时候有问题，主要是想引用url

```
@misc{FracFocus,
  title = {{What Chemicals Are Used} Ground Water Protection Council and Intersatate Oil and Gas Compact Commission},
  howpublished = {\url{http://fracfocus.org/chemical-use/what-chemicals-are-used}},
  note = {Accessed: 2020-04-27}
}
```

```
Package natbib Warning: Citation `FracFocus' on page 2 undefined on input line
15.
Package natbib Warning: There were undefined citations.
```

在没有这类引用的时候没有问题。

请问有什么解决办法吗？

**Comment by ycli0536** [comment]
bat例子见https://github.com/HawkTom/sustech-hithesis

**Comment by dustincys** [comment]
无法引用url，是根据窝工规范要求，不许引用。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yinchu Li <notifications@github.com&gt;
发送时间: 2020年5月1日 03:34
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 无法引用bib中的misc类，如何引用url？ (#52)





 
bat例子见https://github.com/HawkTom/sustech-hithesis

**Comment by ycli0536** [comment]
> 无法引用url，是根据窝工规范要求，不许引用。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yinchu Li <notifications@github.com&gt; 发送时间: 2020年5月1日 03:34 收件人: dustincys/hithesis <hithesis@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[dustincys/hithesis] 无法引用bib中的misc类，如何引用url？ (#52) bat例子见https://github.com/HawkTom/sustech-hithesis — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，了解了。谢谢！

**Comment by ycli0536** [comment]
那可以引用数据库（文献标志代码为[DB]）格式吗

**Comment by Poofee** [comment]
去问你导师呗



---原始邮件---
发件人: "Yinchu Li"<notifications@github.com&gt;
发送时间: 2020年5月3日(周日) 下午2:13
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [dustincys/hithesis] 无法引用bib中的misc类，如何引用url？ (#52)




 
那可以引用数据库（文献标志代码为[DB]）格式吗

**Comment by ycli0536** [comment]
> 去问你导师呗
> […](#)
> ---原始邮件--- 发件人: "Yinchu Li"<notifications@github.com&gt; 发送时间: 2020年5月3日(周日) 下午2:13 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [dustincys/hithesis] 无法引用bib中的misc类，如何引用url？ (#52) 那可以引用数据库（文献标志代码为[DB]）格式吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

主要是因为引用了url编译后不能成功引用啊，想有没有曲线救国的方法，如果没有就不引用了
