### ISSUE TITLE
[报错]\Bbbk命令已被定义

### ISSUE THREAD

**Issue by ThinkingMarmot** [dustincys/hithesis#54]
LaTeX初学者。
平台：Win10，TeXlive 2020，编辑器：TeXstudio
运行实例文件main.tex，报错：amssymb.sty, error，line261, Command `\Bbbk' already defined. ...ol{\Bbbk} {\mathord}{AMSb}{"7C}。

**Comment by Poofee** [comment]
打开amssymb.sty，把\BBBK注释掉



---原始邮件---
发件人: "ThinkingMarmot"<notifications@github.com&gt;
发送时间: 2020年5月8日(周五) 晚上10:12
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dustincys/hithesis] [报错]\Bbbk命名已被定义 (#54)




 
LaTeX初学者。
 平台：Win10，TeXlive 2020，编辑器：TeXstudio
 运行实例文件main.tex，报错：amssymb.sty, error，line261, Command `\Bbbk' already defined. ...ol{\Bbbk} {\mathord}{AMSb}{"7C}。

**Comment by ThinkingMarmot** [comment]
已解决，非常感谢。

**Comment by dustincys** [comment]
根据这里的描述https://pctex.com/kb/86.html，MTPro2 fonts contain all of the symbols provided by amssymb. 应该是这个package更新之后出现了重复定义。
