### ISSUE TITLE
目录黑体

### ISSUE THREAD

**Issue by maye1998** [dustincys/hithesis#55]
![image](https://user-images.githubusercontent.com/61866921/81502718-218ffb80-9312-11ea-9d37-8b57d1e4dfaf.png)
您好，请问目录中这几个第x章xxx，摘要，Abstract怎么设置加粗呢？本科生给的模板里这些是加粗的（好像模板里在正中央的都是加粗的，包括目录这俩字也是）。谢谢您

**Comment by Poofee** [comment]
没必要纠结这个吧，老师让你改你再改呗



---原始邮件---
发件人: "maye1998"<notifications@github.com&gt;
发送时间: 2020年5月10日(周日) 晚上11:34
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dustincys/hithesis] 目录黑体 (#55)




 

 您好，请问目录中这几个第x章xxx，摘要，Abstract怎么设置加粗呢？本科生给的模板里这些是加粗的（好像模板里在正中央的都是加粗的，包括目录这俩字也是）。谢谢您

**Comment by maye1998** [comment]
> 没必要纠结这个吧，老师让你改你再改呗
> […](#)
> ---原始邮件--- 发件人: "maye1998"<notifications@github.com&gt; 发送时间: 2020年5月10日(周日) 晚上11:34 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [dustincys/hithesis] 目录黑体 (#55) 您好，请问目录中这几个第x章xxx，摘要，Abstract怎么设置加粗呢？本科生给的模板里这些是加粗的（好像模板里在正中央的都是加粗的，包括目录这俩字也是）。谢谢您 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 没必要纠结这个吧，老师让你改你再改呗
> […](#)
> ---原始邮件--- 发件人: "maye1998"<notifications@github.com&gt; 发送时间: 2020年5月10日(周日) 晚上11:34 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [dustincys/hithesis] 目录黑体 (#55) 您好，请问目录中这几个第x章xxx，摘要，Abstract怎么设置加粗呢？本科生给的模板里这些是加粗的（好像模板里在正中央的都是加粗的，包括目录这俩字也是）。谢谢您 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 没必要纠结这个吧，老师让你改你再改呗
> […](#)
> ---原始邮件--- 发件人: "maye1998"<notifications@github.com&gt; 发送时间: 2020年5月10日(周日) 晚上11:34 收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [dustincys/hithesis] 目录黑体 (#55) 您好，请问目录中这几个第x章xxx，摘要，Abstract怎么设置加粗呢？本科生给的模板里这些是加粗的（好像模板里在正中央的都是加粗的，包括目录这俩字也是）。谢谢您 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

得，那俺就开始划水论文了

**Comment by dustincys** [comment]
已经添加目录黑体选项
