### ISSUE TITLE
支持overleaf 吗

### ISSUE THREAD

**Issue by lingtengqiu** [dustincys/hithesis#57]

**Comment by dustincys** [comment]
不支持，之后也不考虑支持。据一些大侠称，overleaf有编译时长限制。详细如下


先说overleaf优点如何不容易体现在hithesis 上的理由：overleaf的优势越来越不明显。

多人合作？GitHub private repo 有3人合作免费 其他bitbucket gitee什么的更多

即拿即用？ docket image tiny-hithesis 完全可以实现即拿即用

Website客户端？使用手机平板写论文?这种屏幕大鼠标键盘弱的设备适合读，不适合写，很难说这是优势。另外web编辑器怎么和emacs相提并论？

浏览历史？git 更和谐

云存储不丢失？github private repo 干嘛的？

Overleaf的最大缺点是环境单一，即只能latex 写作。没办法和R python Perl ruby lua matlab octave等融合。动态作图场景就只能反反复复手动收集图片再上传。另外如果使用pgfplot统计作图需要上传大量数据，任何云平台团队在如何创收上使用数学模型卡的死死的。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lingteng Qiu <notifications@github.com&gt;
发送时间: 2020年5月15日 01:41
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 支持overleaf 吗 (#57)

**Comment by Poofee** [comment]
啥叫支持？自己上传到overleaf去编译不就好了？
