### ISSUE TITLE
有关威海校区本科模板

### ISSUE THREAD

**Issue by specialpointcentral** [dustincys/hithesis#59]
威海校区本科模板现在有几个问题：
1. 封面首页不同。不需要生成first page：
https://github.com/dustincys/hithesis/blob/10b4e625dc03aa1daddb7e33a84c96f34db89a53/hithesis.dtx#L2617-L2618
2. 标题及页眉不含有`威海`字样，即这个和本部同
3. 封皮可能与本部不同，这个有待查证。但给的模板上面，按照本部和威海比对，威海没有做段前段后设置，导致行距较本部窄。

**Comment by MayeZhang** [comment]
仔细看了一下还真是这样

**Comment by Riqzz** [comment]
反应一个问题，论文页脚页码处两侧应该有短线，像这样：- 1 -

**Comment by dustincys** [comment]
已修改
