### ISSUE TITLE
如何使用\citeauthor

### ISSUE THREAD

**Issue by yvanst** [dustincys/hithesis#62]
你好，我想达到类似`Li et al.` ，`Li 等人` 这样的效果，我看到Latex中是用`\citeauthor{}`这样的方法做到，但是我无法在hithesis中直接使用，我也没有在introduction.tex中找到相关的说明，请问有什么方法可以支持这个用法吗？

**Comment by Poofee** [comment]
不符合规范，



---原始邮件---
发件人: "yvanst"<notifications@github.com&gt;
发送时间: 2020年6月5日(周五) 下午3:19
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dustincys/hithesis] 如何使用\citeauthor (#62)




 
你好，我想达到类似Li et al. ，Li 等人 这样的效果，我看到Latex中是用\citeauthor{}这样的方法做到，但是我无法在hithesis中直接使用，我也没有在introduction.tex中找到相关的说明，请问有什么方法可以支持这个用法吗？
