### ISSUE TITLE
参考文献中的会议文章和书籍引用会出现[S.1.]或[出版地不详]，如何去除

### ISSUE THREAD

**Issue by ThinkingMarmot** [dustincys/hithesis#63]
win10平台，texlive2020+texstudio
当引文数据中没有地址信息时，中文文献会出现[出版地不详]的字样，英文文献会出现[S.1.]的字样。这好像是国标GB7714-2015所规定的，但是在本部的书写范例中并没有这种格式，而是直接省略。请问如何去除？谢谢。

**Comment by Poofee** [comment]
你自己在bib里把出版地加上



---原始邮件---
发件人: "ThinkingMarmot"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 上午10:39
收件人: "dustincys/hithesis"<hithesis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dustincys/hithesis] 参考文献中的会议文章和书籍引用会出现[S.1.]或[出版地不详]，如何去除 (#63)




 
win10平台，texlive2020+texstudio
 当引文数据中没有地址信息时，中文文献会出现[出版地不详]的字样，英文文献会出现[S.1.]的字样。这好像是国标GB7714-2015所规定的，但是在本部的书写范例中并没有这种格式，而是直接省略。请问如何去除？谢谢。

**Comment by dustincys** [comment]
直接修改bbl 文件，然后编译一次。
