### ISSUE TITLE
目录格式问题

### ISSUE THREAD

**Issue by ThinkingMarmot** [dustincys/hithesis#65]
LaTeX初学者
平台：windows 10，texlive2020，texstudio
1. 如何将目录中的Abstract全大写为ABSTRACT；
2. 目录中前文项与正文项之间的间距太大，如何调整为与正文项间的间距相同。

尝试看了一下文档类的源码并修改，但似乎已超出了我的能力范围
![now](https://user-images.githubusercontent.com/50788192/85190286-63d13300-b2e9-11ea-84a4-e99047073afe.jpg)

**Comment by Poofee** [comment]
阅读选项设置

% 此处选项中不要有空格
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 必填选项
% type=doctor|master|bachelor|postdoc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 选填选项（选填选项的缺省值已经尽可能满足了大多数需求，除非明确知道自己有什么
% 需求）
% campus=shenzhen|weihai|harbin
%   含义：校区选项，默认harbin
% glue=true|false
%   含义：由于我工规范中要求字体行距在一个闭区间内，这个选项为true表示tex自
%   动选择，为false表示区间内一个最接近版心要求行数的要求的默认值，缺省值为
%   false。
% tocfour=true|false
%   含义：是否添加第四级目录，只对本科文科个别要求四级目录有效，缺省值为
%   false
% fontset=windows|mac|ubuntu|fandol|adobe
%   含义：设置字体，默认情况会自动识别系统，然后设置字体。后两个是开源字体，自行
%   下载安装后设置使用。windows是中易字库，窝工默认常用字体，绝对没毛病。mac和
%   ubuntu 默认分别是华文和思源字库，理论上用什么字库都行。后两种开源字库的安装
%   方法到谷歌上百度一下什么都有了。Linux非ubuntu发行版、非x86架构机器等如何运行
%   可到github issue上讨论。
% tocblank=true|false
%   含义：目录中第一章之前，是否加一行空白。缺省值为true。
% chapterhang=true|false
%   含义：目录的章标题是否悬挂居中，规范中要求章标题少于15字，所以这个选项
%   有无没什么用，除了特殊需求。缺省值为true。
% fulltime=true|false
%   含义：是否全日制，缺省值为true。非全日制如同等学力等，要在cover中设置类
%   型，封面中不同格式
% subtitle=true|false
%   含义：论文题目是否含有副标题，缺省值为false，如果有要在cover中设置副标
%   题内容，封面中显示。
% newgeometry=one|two
%   含义：规范中的自相矛盾之处，版芯是否包含页眉页脚，旧方法是按照包含页眉
%   页脚来设置。该选项是多选选项，如果没有这个选项，缺省值是旧模板的版芯设
%   置方法，如果设置该选项one或two，分别对应两种页眉页码对应版芯线的相对位
%   置。第一种是严格按照规范要求，难看。第二种微调了页眉页码位置，好一点。
% debug=true|false
%   含义：是否显示版芯框和行号，用来调试。默认否。
% openright=true|false
%   含义：博士论文是否要求章节首页必须在奇数页，此选项不在规范要求中，按个
%   人喜好自行决定。 默认否。注意，窝工的默认情况是打印版博士论文要求右翻页
%   ，电子版要求非右翻页且无空白页。如果想DIY（或身不由己DIY）在什么地方右
%   翻页，将这个选项设置为false，然后在目标位置添加`\cleardoublepage`命令即
%   可。
% library=true|false
%   含义：是否为提交到图书馆的电子版。默认否。注意：如果设置成true，那么
%   openright选项将被强制转换为false。
% capcenterlast=true|false
%   含义：图题、表题最后一行是否居中对齐（我工规范要求居中，但不要求居中对
%   齐），此选项不在规范要求中，按个人喜好自行决定。默认否。
% subcapcenterlast=true|false
%   含义：子图图题最后一行是否居中对齐（我工规范要求居中，但不要求居中对齐
%   ），此选项不在规范要求中，按个人喜好自行决定。默认否。
% absupper=true|false
%   含义：中文目录中的英文摘要在中文目录中的大小写样式歧义，在规范中要求首
%   字母大写，在work样例中是全大写。该选项控制是否全大写。默认否。
% bsmainpagenumberline=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否在正文中显示页码横线，默认否。
% bsfrontpagenumberline=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否在前文中显示页码横线，默认否。
% bsheadrule=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否显示页眉横线，默认显示。
% splitbibitem=true|false
%   含义：参考文献每一个条目内能不能断页，应广大刀客要求添加。默认否。
% newtxmath=true|false
%   含义：数学字体是否使用新罗马。默认是。

**Comment by ThinkingMarmot** [comment]
原来就在文档类选项中，多谢，已经解决了。
