### ISSUE TITLE
windows 10 中使用Docker编译方式，在make thesis 阶段报错

### ISSUE THREAD

**Issue by Vccxx** [dustincys/hithesis#67]
**Describe the bug**
 make: *** No rule to make target 'hithesisbook.cls', needed by 'thesis.pdf'.  Stop.
已经使用`run --rm -it-v %cd%:/home/runner dustincys/tinytex-hithesis:latest`进入docker交互shell检查目录挂载情况：目录挂载没有问题。

**To Reproduce**
` docker pull dustincys/tinytex-hithesis:latest`
`git clone https://github.com/dustincys/hithesis.git`
`cd hithesis\examples\hitbook\chinese`
`docker run --rm -i  -v %cd%:/home/runner dustincys/tinytex-hithesis:latest make thesis`

**Screenshots**
![微信图片_20200908165803](https://user-images.githubusercontent.com/21141761/92456110-17650780-f1f5-11ea-9dc0-45f43ae38c4e.png)

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by dustincys** [comment]
是不是没有抽取格式，先要抽取格式，然后在编译
根据Github Action 结果显示，dockerhub没有bug

**Comment by Vccxx** [comment]
抽取格式是怎么操作，我在readme里面好像没有看到对应的指南

**Comment by Vccxx** [comment]
哦我懂了，在docker里面还需要按照readme里面提及的编译流程走。我犯了低级错误，耽误你时间了，抱歉
