### ISSUE TITLE
哈尔滨校区研究生开题报告模板又双叒叕变了

### ISSUE THREAD

**Issue by joyqat** [dustincys/hithesis#68]
http://hitgs.hit.edu.cn/_upload/article/files/f5/98/ba0823ee49ea8365efb777a66d58/67ba646d-5eae-4fb9-864a-4b31becd3088.doc
主要几个变化
![image](https://user-images.githubusercontent.com/10184445/92846298-87080c00-f41a-11ea-8a2e-65922803c971.png)
- 前两行字体中间有了2磅间距
- 页面底部时间没了
稍后我看下能不能搞个PR

**Comment by joyqat** [comment]
- 字间距不知道怎么操作
- 页面底部时间的话直接删掉就好

**Comment by Poofee** [comment]
开个题而已，才几页……word呗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: joyqat <notifications@github.com&gt;
发送时间: 2020年9月11日 13:21
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 哈尔滨校区研究生开题报告模板又双叒叕变了 (#68)






字间距不知道怎么操作

页面底部时间的话直接删掉就好

**Comment by dustincys** [comment]
@joyqat 参考的规范在哪个网页上？

**Comment by dustincys** [comment]
已经修改
