### ISSUE TITLE
硕士开题报告的行距似乎太小

### ISSUE THREAD

**Issue by miRoox** [dustincys/hithesis#69]
**描述bug**
如图：

![hithesis-linespread](https://user-images.githubusercontent.com/20090991/93018699-2b00db80-f604-11ea-9cc2-759b41e9fb1a.png)

一页有将近四十行。而按学校提供模板的要求，正文一页应在33行左右。

> 六、字体、字号及其他规定
> &emsp;论文中所用中文字体（除各级标题外）为宋体，各级标题用黑体；论文中所用数字、英文为新罗马字体。
> &emsp;节标题&emsp;&emsp;&emsp;小3号字，建议段前0.5行，段后0.5行；
> &emsp;条标题&emsp;&emsp;&emsp;4号字，建议段前0.5行，段后0.5行；
> &emsp;款、项标题&emsp;小4号字， 建议段前0行，段后0行；
> &emsp;正文&emsp;&emsp;&emsp;&emsp;小4号字，建议段前0行，段后0行，每页约33行。

如码：

`report.tex`:
```tex
\documentclass[toc=true,type=master,stage=opening]{hithesisart}
\usepackage{zhlipsum}
% 中略
\input{body/opening}
% 下略
```

`body/opening.tex`:
```tex
\section{课题来源及研究的目的和意义}

\subsection{课题来源或研究背景}

\zhlipsum[1]

\subsection{研究的目的及意义}

\zhlipsum[2-3]

% 下略
```

**Comment by dustincys** [comment]
@miRoox 
这个参考的规范在哪个网页上？应该添加到Readme中

**Comment by miRoox** [comment]
@dustincys 
参考的模板在研究生教育管理系统的“开题/中期信息录入”可以找到，但是没有登录的话好像是没有访问权限的……

**Comment by dustincys** [comment]
已经修改
