### ISSUE TITLE
win10 编译报错 

### ISSUE THREAD

**Issue by Poofee** [dustincys/hithesis#70]
**描述bug类型**
win10 miktex 编译报错 Environment CJKfilltwosides undefined. 
- 校区（哈尔滨/威海/深圳？）：
哈尔滨
- 学位（本/硕/博？）：
博
- 论文类型（毕业论文/开题/中期/博后/English Version？）：
毕业论文
- 证据（与规范不符/与word模板不符？）：

![Snipaste_2020-09-18_11-32-16](https://user-images.githubusercontent.com/10039950/93552298-bf6f9300-f9a2-11ea-93eb-ca38d8901d49.png)

然后我在网上搜索，发现把
\RequirePackage{CJKfntef}
改为
\RequirePackage{xeCJKfntef}
就好了

什么原因？

**Comment by miRoox** [comment]
大概是今年的某次更新移除了 xeCJK + CJKfntef 会加载 xeCJKfntef 的特性。见 <https://github.com/CTeX-org/ctex-kit/issues/449>

**Comment by jsaon945** [comment]
兄弟你太给力了，我也遇到跟你一样的问题，整了半天没弄好。本来想过来重新下载一份试试，结果无意中看到你的评论，问题迎刃而解啊！

**Comment by dustincys** [comment]
已修复
