### ISSUE TITLE
English Version example 无法编译

### ISSUE THREAD

**Issue by liziwl** [dustincys/hithesis#74]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕士

- 论文类型（毕业论文/开题/中期/博后/English Version？）：English Version？

目录下 /examples/hitbook/english 按照教程无法编译

## 运行代码 at texlive 2019 in Ubuntu
```
latex hithesis.ins
xelatex -shell-escape thesis.tex
bibtex thesis
xelatex -shell-escape thesis.tex
xelatex -shell-escape thesis.tex
```

**Comment by dustincys** [comment]
贴一下output, 
可能
１. 格式没有正确生成
２. 没有安装好tex
用docker是肯定没问题的。

**Comment by dustincys** [comment]
由于没有回应且github action 显示docker编译成功，关闭这个issue
