### ISSUE TITLE
哈工大深圳硕士论文第三页显示英文

### ISSUE THREAD

**Issue by amyzx** [dustincys/hithesis#75]
请问第三页中论文标题前默认的文字如何改成 A dissertation submitted in partial fulfillment of the requirements for the academic degree of Master of Engineering。目前我用的模板里文字为 Dissertation for the Master’s Degree in Engineering。

这个是不是需要改哪个设置呢？谢谢

**Comment by dustincys** [comment]
是《规范》里规定的么？在哪个网页，统一修改可以方便其他同学

**Comment by amyzx** [comment]
> 是《规范》里规定的么？在哪个网页，统一修改可以方便其他同学


我下载的  http://due.hitsz.edu.cn/info/1211/1859.htm  这个链接里哈工大（深圳）学术规范及硕士学位论文撰写文件包（2019年版）的第二个文件，

在  \2.硕士论文撰写格式相关文件 (1)\2.硕士论文撰写格式相关文件\1.深圳校区硕士论文格式文件\1.2哈尔滨工业大学（深圳）研究生学位论文书写范例.doc   
中第4页看到的文字显示为 A dissertation submitted in partial fulfillment of the requirements for the academic degree of  Master of Engineering。

然后我看去年师兄师姐提交的论文也是显示上述文字，我不知道怎么设置模板里的选项，目前默认编译完是显示的Dissertation for the Master’s Degree in Engineering。谢谢！

**Comment by dustincys** [comment]
已修改

**Comment by amyzx** [comment]
> 已修改

感谢，我重新下载了您更新的 hithesis.dtx 文件，并且替换了之后，在命令行里运行 lualatex hithesis.ins，然后编译成功。

现在显示已经正常，非常感谢！
