### ISSUE TITLE
深圳校区关于页眉最新规范要求于现有页眉格式不一致

### ISSUE THREAD

**Issue by wuxiaoqiang12** [dustincys/hithesis#76]
**描述bug类型**

- 校区：深圳

- 学位：硕士

- 论文类型：毕业论文

- 证据：深圳校区对页眉给出了新的规范

- 证据所在网页：http://due.hitsz.edu.cn/info/1211/1859.htm

**描述bug具体信息** 

窝工在《哈尔滨工业大学（深圳）硕士学位论文格式要求及审查要点》规范第6页5.1节规定格式为：
 除**摘要 、 目录的页眉对应本页内容字样**以外从绪论开始， 页眉均为 “哈尔滨工业大学 □ 学硕士学位论文”。
如图：
![image](https://user-images.githubusercontent.com/39110174/97455738-8cf47680-190e-11eb-865d-93b53315685e.png)

hithesis的格式为
现有页眉均为哈尔滨工业大学（深圳）工学硕士学位论文。
如图：
![image](https://user-images.githubusercontent.com/39110174/97455827-a269a080-190e-11eb-9696-26cad62f6bcd.png)

**Comment by dustincys** [comment]
已更新。
