### ISSUE TITLE
深圳校区 硕士论文 发现若干问题

### ISSUE THREAD

**Issue by Tramp6** [dustincys/hithesis#78]
按照学校教务处通知的论文模板
http://due.hitsz.edu.cn/info/1211/1859.htm
其中有 哈尔滨工业大学（深圳）全日制硕士研究生学位论文书写范例
1.Tex模板中目录物理量符号表和第一章中间存在一行空格。

![001](https://user-images.githubusercontent.com/36286950/97528931-d1087980-19e9-11eb-9da9-22236821b0a8.png)
![002](https://user-images.githubusercontent.com/36286950/97528933-d2d23d00-19e9-11eb-9382-a81875c7181f.png)

2.新的论文模板存在一个英文目录，麻烦掌门考虑一下手动添加还是自动添加。

![003](https://user-images.githubusercontent.com/36286950/97528935-d36ad380-19e9-11eb-8c4d-b66b64d784d5.png)

3.新的论文模板单行中文字数由35改为33个
![004](https://user-images.githubusercontent.com/36286950/97529064-1462e800-19ea-11eb-804a-da99a0b35bd3.png)
![005](https://user-images.githubusercontent.com/36286950/97529066-15941500-19ea-11eb-89f4-ecc28fe83c7f.png)

4.另外，我在知网观察往届我校提交论文的封面和我们的Tex模板相比，缺少学校校徽。图中论文是知网下载的。
![006](https://user-images.githubusercontent.com/36286950/97529239-715e9e00-19ea-11eb-8d34-053e966e2fe7.png)
![007](https://user-images.githubusercontent.com/36286950/97529307-96531100-19ea-11eb-9a67-7102d629a1a6.png)

麻烦掌门大人能够做出修改。辛苦了。

**Comment by dustincys** [comment]
第一个仔细阅读注释，已经有开关控制。
第二个已添加非博士生英文目录开关。
第三个已修改每行34个字。
第四个不在规范和范例中，所以以word范例为准，不添加校徽。

**Comment by Tramp6** [comment]
> 第一个仔细阅读注释，已经有开关控制。
> 第二个已添加非博士生英文目录开关。
> 第三个已修改每行34个字。
> 第四个不在规范和范例中，所以以word范例为准，不添加校徽。

十分感谢掌门帮助
