### ISSUE TITLE
深圳校区英文硕Theorem标题过长无法自动换行

### ISSUE THREAD

**Issue by yangyi724** [dustincys/hithesis#79]
**描述请求添加特性的类型**
Theorem 标题过长自动换行
- 校区（哈尔滨/威海/深圳？）：
深圳
- 学位（本/硕/博？）：
硕 
- 论文类型（毕业论文/开题/中期/博后/English Version？）：
English Version

**描述特性具体信息** 

Theorem 标题过长时，现有版本无法自动换行

![image](https://user-images.githubusercontent.com/26060578/98081870-d4e93f80-1eb2-11eb-9f23-016eb8248a1f.png)

**Comment by dustincys** [comment]
如果按照中文中定理格式，可以换行

**Comment by dustincys** [comment]
既然没有意见
