### ISSUE TITLE
深圳校区与2020年11月3号发布的开题报告模板中，更新了部分模板和内容

### ISSUE THREAD

**Issue by RManLuo** [dustincys/hithesis#80]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：
深圳
- 学位（本/硕/博？）：
本
- 论文类型（毕业论文/开题/中期/博后/English Version？）：
开题
- 证据（与规范不符/与word模板不符？）：
与word模板不符？
- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：
http://due.hitsz.edu.cn/info/1341/2835.htm
http://due.hitsz.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1481660265&wbfileid=4626652
**描述bug具体信息** 
深圳校区与2020年11月3号发布的开题报告模板中，将logo换成了新的版本。
窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：
![image](https://user-images.githubusercontent.com/34737002/99067468-bd623300-25e5-11eb-998b-76ce5c758295.png)

hithesis的格式为
如图：
![image](https://user-images.githubusercontent.com/34737002/99070017-6e6acc80-25ea-11eb-88dd-32157cb98aae.png)

可能需要更新一下logo图片

**Comment by RManLuo** [comment]
另外底下的\hit@shenzhen@schoolbottommark也需要修改成：“哈尔滨工业大学（深圳）教务部制”

**Comment by dustincys** [comment]
有大侠已经更改好准备提交PR

**Comment by Wolfybox** [comment]
> 有大侠已经更改好准备提交PR Raymond Luo <notifications@github.com> writes:
> […](#)
> Assigned #80 to @dustincys. -- You are receiving this because you were assigned. Reply to this email directly or view it on GitHub: [#80 (comment)](https://github.com/dustincys/hithesis/issues/80#event-3993059321)

请问深圳校区开题报告的这个changes更新了吗？

**Comment by dustincys** [comment]
@Wolfybox 沒有，看来什么都要某自己来……

**Comment by syvshc** [comment]
http://due.hitsz.edu.cn/info/1341/3863.htm 根据更新的规范, 深圳校区又更新规范啦 哈哈……所以这个issue我直接关闭了哈
