### ISSUE TITLE
2020年深圳校区word模板与latex不一致

### ISSUE THREAD

**Issue by cjliux** [dustincys/hithesis#81]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：
与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：
http://due.hitsz.edu.cn/info/1211/1859.htm

**描述bug具体信息** 
（以下所有图，左侧为latex编译结果，右侧为word转pdf）

（1）页眉过高：（word模板中，页眉字上方处于31mm处，而latex处于21mm处）
![1](https://user-images.githubusercontent.com/14961563/101271170-75d16000-37bb-11eb-8104-0645d6e3476c.png)
（2）页码过低：（差距较不明显）
![2](https://user-images.githubusercontent.com/14961563/101271214-baf59200-37bb-11eb-817d-5821df5ac756.png)
（3）行距略大且不均匀：
满字情况下，行距约3.5mm，正确为严格3mm（包含正文行距及页眉与正文间隔）
![3](https://user-images.githubusercontent.com/14961563/101271268-5981f300-37bc-11eb-8d7d-1e38b3f31add.png)

**Comment by dustincys** [comment]
@cjliux 最后一个图片不好。

从PlutoThesis升级到hithesis时候，我发现原PlutoThesis的行距不正确。然后仔细计算一下行距

需要的单位如下：

- [小四号字体12bp](https://baike.baidu.com/item/%E7%A3%85%E5%80%BC)
- [1bp = 0.35277mm](https://tex.stackexchange.com/questions/8260/what-are-the-various-units-ex-em-in-pt-bp-dd-pc-expressed-in-mm)
- [窝工要求：约33行3~4mm行距，版芯高240mm+-2](http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp)

然而窝工老板们要求必须33行。然后有这样公式：

正文最小：

> 33(行)*12(bp/行)*0.35277(mm/bp) + 32(行) * 3(mm/行)＝235.6969(mm)

正文最大：

> 33(行)*12(bp/行)*0.35277(mm/bp)` + 32(行) * 3(mm/行)＝267.6969(mm)

这说明，**_窝工版芯必然不能包括页眉页脚，因为240mm正文刚刚符合要求的区间了_**。

然后我整了个开关，在设置glue=false时，行距强制最小值，不能浮动了，如果glue=true，行距应该在3~4mm之间动态浮动，这不就符合窝工一贯尿性的“规格严格但不包括论文格式”的作风了么？

回头说最后一个图片为什么不好，

1. 看不到满页全是正文（没有标题），无法判断是不是33行。
2. 没有打印出来，然后格尺放上去，分别量一下latex和word两个版本行距是不是3mm

**Comment by cjliux** [comment]
发现了一个问题，字体的大小单位是pt，而不是bp。12bp换算为约4.23324，而12pt换算为约3.7mm，所以会导致间距过大（平均约3.5mm）。虽然也在规范要求的3~4mm之间，但页眉过高感觉比较突兀。

按照pt计算的行距3~4mm对应的33行版芯高度范围大约在218.1mm~250.1之间，所以规范文件写的版芯150mm x 240mm显然是合理的。

而实际word模板除去页边距为150mm x 229mm，内容34行34列，行距约3mm，并不符合规范。这个就比较尴尬了。

**Comment by cjliux** [comment]
word模板虽然格式不正确，但可以作为一个参考

**Comment by dustincys** [comment]
> 发现了一个问题，字体的大小单位是pt，而不是bp。12bp换算为约4.23324，而12pt换算为约3.7mm，所以会导致间距过大（平均约3.5mm）。虽然也在规范要求的3~4mm之间，但页眉过高感觉比较突兀。
> 
> 按照pt计算的行距3~4mm对应的33行版芯高度范围大约在218.1mm~250.1之间，所以规范文件写的版芯150mm x 240mm显然是合理的。
> 
> 而实际word模板除去页边距为150mm x 229mm，包含页眉距3mm，页眉高5mm，页脚距3mm，刚好240mm。
> 但内容34行34列，行距约3mm，显然不符合规范，比较尴尬。

根据
https://en.wikipedia.org/wiki/Point_%28typography%29
中说明，MS word中pt与latex中pt定义不一样，word中pt就是latex中bp

**Comment by cjliux** [comment]
好像确实是这样，不过我量的是pdf里面的字体高度（确实3.7mm），不知道是不是因为字体上下有留白的原因？

**Comment by dustincys** [comment]
字距可以再开一个issue
