### ISSUE TITLE
哈尔滨 - 博士 - 毕业论文 - 引用文献格式 - 冒号问题

### ISSUE THREAD

**Issue by ZhaopeiG** [dustincys/hithesis#83]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与规范及word模板不符合

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp
http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp

**描述bug具体信息** 

窝工在（规范/word模板中）第（xxx）行规定格式为：

在研究生学位论文撰写规范（http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp），2.14 参考文献部分，所有涉及到冒号（：）的部分，规范中冒号更贴近前一个字符，而hithesis中冒号是居中的，进而被老师们怀疑冒号前多了空格。
如图：
![image](https://user-images.githubusercontent.com/3530785/101899997-b3821e80-3be9-11eb-9acd-9004ae209f80.png)

窝工规范或者word模板中：参考文献文献部分冒号也是更贴近前一个字符。
如图：
![image](https://user-images.githubusercontent.com/3530785/101900362-5044bc00-3bea-11eb-9fd1-bb8b35d4e9f6.png)

hithesis的格式为
如图：
![image](https://user-images.githubusercontent.com/3530785/101900061-cf85c000-3be9-11eb-869b-6f1868e778fb.png)

可明显看出冒号居中，而按照规范，应该更靠近前一个字符。
=====================================================
非常感谢大神博士开发和维护这套模板，弥补了工大和世界一流大学接轨过程中的一个缺项（美国的许多大学好多都有latex模板），大神博士是在做一个正确和有意义的事情。
再次表示感谢~

**Comment by Poofee** [comment]
那是中文冒号和英文冒号



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhaopei G <notifications@github.com&gt;
发送时间: 2020年12月11日 19:57
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 哈尔滨 - 博士 - 毕业论文 - 引用文献格式 - 冒号问题 (#83)





 
描述bug类型
  
 
校区（哈尔滨/威海/深圳？）：哈尔滨
 

 
学位（本/硕/博？）：博
 

 
论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文
 

 
证据（与规范不符/与word模板不符？）：与规范及word模板不符合
 

 
证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp
 http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp
 
 
描述bug具体信息
 
窝工在（规范/word模板中）第（xxx）行规定格式为：
 
在研究生学位论文撰写规范（http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp），2.14 参考文献部分，所有涉及到冒号（：）的部分，规范中冒号更贴近前一个字符，而hithesis中冒号是居中的，进而被老师们怀疑冒号前多了空格。
 如图：
 
 
窝工规范或者word模板中：参考文献文献部分冒号也是更贴近前一个字符。
 如图：
 
 
hithesis的格式为
 如图：
 
 
可明显看出冒号居中，而按照规范，应该更靠近前一个字符。
 
非常感谢大神博士开发和维护这套模板，弥补了工大和世界一流大学接轨过程中的一个缺项（美国的许多大学好多都有latex模板），大神博士是在做一个正确和有意义的事情。
 再次表示感谢~

**Comment by ZhaopeiG** [comment]
> 那是中文冒号和英文冒号 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Zhaopei G <notifications@github.com&gt; 发送时间: 2020年12月11日 19:57 收件人: dustincys/hithesis <hithesis@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[dustincys/hithesis] 哈尔滨 - 博士 - 毕业论文 - 引用文献格式 - 冒号问题 (#83) 描述bug类型 校区（哈尔滨/威海/深圳？）：哈尔滨 学位（本/硕/博？）：博 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文 证据（与规范不符/与word模板不符？）：与规范及word模板不符合 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp 描述bug具体信息 窝工在（规范/word模板中）第（xxx）行规定格式为： 在研究生学位论文撰写规范（[http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp），2.14](http://hitgs.hit.edu.cn/aa/fd/c3425a109309/page.psp%EF%BC%89%EF%BC%8C2.14) 参考文献部分，所有涉及到冒号（：）的部分，规范中冒号更贴近前一个字符，而hithesis中冒号是居中的，进而被老师们怀疑冒号前多了空格。 如图： 窝工规范或者word模板中：参考文献文献部分冒号也是更贴近前一个字符。 如图： hithesis的格式为 如图： 可明显看出冒号居中，而按照规范，应该更靠近前一个字符。 非常感谢大神博士开发和维护这套模板，弥补了工大和世界一流大学接轨过程中的一个缺项（美国的许多大学好多都有latex模板），大神博士是在做一个正确和有意义的事情。 再次表示感谢~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

参考文献中的冒号，我是无法操作的，我只能填写信息，冒号是模板自动生成的，貌似需要在维护者在模板里面改。

**Comment by Poofee** [comment]
标点符号不都是英文吗？有什么问题

**Comment by ZhaopeiG** [comment]
> 标点符号不都是英文吗？有什么问题

按照工大模板（网页版本和word版本），在视觉上，参考文献中的冒号应该更靠近前一个字符。证据见上边的详细带图反馈。
但是在hithesis编译出的文档中，参考文献中的冒号，在视觉上，更居中，因此被人误认为前面多了空格。证据见上边的详细带图反馈。

而参考文献部分的冒号，不是使用者可以操作的，所以如有可能，需要维护者在核心代码层面更改一下~表示感谢

**Comment by ZhaopeiG** [comment]
> 标点符号不都是英文吗？有什么问题

我说的参考文献中的冒号，是   [地址]：[出版社]  或者 [年份]：[页码]中的冒号。不是使用者填写的内容中的冒号。

**Comment by Poofee** [comment]
我坚持是半角标点，如果你想改就自己去改bst文件

**Comment by ZhaopeiG** [comment]
> 我坚持是半角标点，如果你想改就自己去改bst文件

谢谢告知，是否能做一个选项出来，不讨论是半角还是全角，至少现在的模板和窝工的模板，在这一点上是不一致的。

**Comment by Poofee** [comment]
不关我事。。。你去求大佬

**Comment by ZhaopeiG** [comment]
> 不关我事。。。你去求大佬

哪里跑~

**Comment by dustincys** [comment]
窝工规范要求使用国标2005参考文献样式，需要对比国标2005之后才能判断到底哪个对哪个错

**Comment by Poofee** [comment]
这样的话太麻烦了吧，英文文献要用英文冒号，中文用中文冒号。。。

**Comment by dustincys** [comment]
看起来，不仅仅冒号是全角，似乎逗号也是

**Comment by Poofee** [comment]
那个bst不是各个学校都用的一样的吗……



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dustin <notifications@github.com&gt;
发送时间: 2020年12月12日 09:36
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Poofee <poofee@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 哈尔滨 - 博士 - 毕业论文 - 引用文献格式 - 冒号问题 (#83)






看起来，不仅仅冒号是全角，似乎逗号也是

**Comment by ZhaopeiG** [comment]
> 国标2005参考文献样式

感谢回复~~
我找到一个参考文献格式国家标准(GB-T7714-2005)（https://wenku.baidu.com/view/3103b9b750e2524de5187e8f.html）
其中4.1.2部分，如图所示
![image](https://user-images.githubusercontent.com/3530785/101973218-53cf5600-3c71-11eb-8410-c68fe9091177.png)
无论是英文还是中文，冒号，在视觉上都更贴近前一个字符。也因此hithesis的格式被人怀疑冒号前被多加了空格。
============
非常感谢你们的开发和维护工作，我只是反馈bug

**Comment by dustincys** [comment]
fixd

**Comment by Poofee** [comment]
只是改了间隙，但是Word里的中文冒号比英文冒号更粗一些。。。。差别还是很明显的

**Comment by dustincys** [comment]
> 只是改了间隙，但是Word里的中文冒号比英文冒号更粗一些。。。。差别还是很明显的

word 中是中文冒号。这一点需要再确认GBT2005中是不是明确规定用哪一种标点

**Comment by Poofee** [comment]
目测是中文，但是没明确说
