### ISSUE TITLE
一些格式的差异

### ISSUE THREAD

**Issue by Poofee** [dustincys/hithesis#85]
今天把论文给我们学院的分委会主席看了，她对比了我的论文和她认可的一本，发现我的版心行间距过大，我的一页最多32行，有的31行，而另一本34行。。。。

还有她或页眉的横线与标题的间隙太小。。。

**Comment by Poofee** [comment]
首次推广LaTeX失败。。。老师认为Word比LaTeX更容易调节，以后工作学生们会用到

**Comment by dustincys** [comment]
各有好处

**Comment by Poofee** [comment]
word的行距跟latex是不是不一样啊，怎么修改



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dustin <notifications@github.com&gt;
发送时间: 2020年12月29日 12:47
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Poofee <poofee@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 一些格式的差异 (#85)





 各有好处 
 
 Sent from my iPhone 
 
 &gt; On Dec 28, 2020, at 7:22 AM, Poofee <notifications@github.com&gt; wrote: 
 &gt;  
 &gt; ﻿ 
 &gt; 首次推广LaTeX失败。。。老师认为Word比LaTeX更容易调节，以后工作学生们会用到 
 &gt;  
 &gt; — 
 &gt; You are receiving this because you were assigned. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dustincys** [comment]
行距之前讨论过，规范和word 矛盾，现在行距采用规范要求的3~4mm

**Comment by Poofee** [comment]
直接设置为word里的1.25倍不可以吗，在哪里设置？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dustin <notifications@github.com&gt;
发送时间: 2020年12月29日 12:50
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Poofee <poofee@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] 一些格式的差异 (#85)





行距之前讨论过，规范和word 矛盾，现在行距采用规范要求的3~4mm

Sent from my iPhone

&gt; On Dec 28, 2020, at 10:48 PM, Poofee <notifications@github.com&gt; wrote:
&gt; 
&gt; ﻿
&gt; word的行距跟latex是不是不一样啊，怎么修改 
&gt; 
&gt; 
&gt; 
&gt; 发自我的iPhone 
&gt; 
&gt; 
&gt; ------------------ 原始邮件 ------------------ 
&gt; 发件人: Dustin <notifications@github.com&amp;gt; 
&gt; 发送时间: 2020年12月29日 12:47 
&gt; 收件人: dustincys/hithesis <hithesis@noreply.github.com&amp;gt; 
&gt; 抄送: Poofee <poofee@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
&gt; 主题: 回复：[dustincys/hithesis] 一些格式的差异 (#85) 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 各有好处 
&gt; 
&gt; Sent from my iPhone 
&gt; 
&gt; &amp;gt; On Dec 28, 2020, at 7:22 AM, Poofee <notifications@github.com&amp;gt; wrote: 
&gt; &amp;gt; 
&gt; &amp;gt; ﻿ 
&gt; &amp;gt; 首次推广LaTeX失败。。。老师认为Word比LaTeX更容易调节，以后工作学生们会用到 
&gt; &amp;gt; 
&gt; &amp;gt; — 
&gt; &amp;gt; You are receiving this because you were assigned. 
&gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
&gt; 
&gt; — 
&gt; You are receiving this because you authored the thread. 
&gt; Reply to this email directly, view it on GitHub, or unsubscribe.
&gt; —
&gt; You are receiving this because you were assigned.
&gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dustincys** [comment]
在设置字体的地方设置
