### ISSUE TITLE
\chapter 标题如何拆分两行？

### ISSUE THREAD

**Issue by Poofee** [dustincys/hithesis#86]
\chapter 使用 \\ 换行发现页眉也变两行了

**Comment by dustincys** [comment]
这个问题已经解决了，新版本，样例中就有

**Comment by Poofee** [comment]
看到了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dustin <notifications@github.com&gt;
发送时间: 2020年12月29日 12:48
收件人: dustincys/hithesis <hithesis@noreply.github.com&gt;
抄送: Poofee <poofee@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[dustincys/hithesis] \chapter 标题如何拆分两行？ (#86)





 这个问题已经解决了，新版本，样例中就有 
 
 Sent from my iPhone 
 
 &gt; On Dec 28, 2020, at 7:15 AM, Poofee <notifications@github.com&gt; wrote: 
 &gt;  
 &gt; ﻿ 
 &gt; \chapter 使用 \ 换行发现页眉也变两行了 
 &gt;  
 &gt; — 
 &gt; You are receiving this because you were assigned. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
