### ISSUE TITLE
tinytex方案中，eps图像无法正常显示

### ISSUE THREAD

**Issue by XioSUN** [dustincys/hithesis#87]
**描述bug类型**
xelatex编译通过但是eps图像无法正常显示，同figures文件夹下换个图像格式，jpeg/pdf/png都可正常显示
- 校区（哈尔滨/威海/深圳？）：
哈尔滨
- 学位（本/硕/博？）：
硕
- 论文类型（毕业论文/开题/中期/博后/English Version？）：
毕业论文
- 证据（与规范不符/与word模板不符？）：
/
- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：
/
**描述bug具体信息** 
使用推荐的docker + tinytex-hithesis方案，编译不报错，但是eps图像无法正常显示
窝工在（规范/word模板中）第（xxx）行规定格式为：
/
如图：
![图片](https://user-images.githubusercontent.com/20400847/111161324-ffbc7080-85d5-11eb-995e-b5e2355f767a.png)
![图片](https://user-images.githubusercontent.com/20400847/111161405-14990400-85d6-11eb-95f4-89b252502026.png)

hithesis的格式为
/

如图：
/
如码：
/

**Comment by XioSUN** [comment]
实际上是所有的eps图像都没法显示，包括封面的学校名eps，对应的位置都是空白
多有打扰～

**Comment by dustincys** [comment]
eps 格式图片越来越不支持，比如透明，试一试用eps2pdf 转换之后，应该就能显示了。

**Comment by XioSUN** [comment]
感谢，使用eps2pdf，确实好使，显示正常。
贴上在线eps2pdf转换工具 https://www.onlineconverter.com/eps-to-pdf
再次感谢~
