### ISSUE TITLE
页眉的线条位置

### ISSUE THREAD

**Issue by jiajun-hit** [dustincys/hithesis#9]
首先感谢无私奉献，我的latex学习便是从这开始的。

右边是《研究生论文书写范例-2011版》用word生成的pdf。可以看到的一个区别是本模板生成的pdf文档的也没位置要偏上一点。我看了以前师兄师姐的硕士论文，页眉位置与范例相同。

我没有很看懂《书写规范中》关于装订、版芯的描述。不过这样没有问题吗？还是我的pdf生成有问题？

MacOS 10.13 用两种方法生成的pdf没有区别。

<img width="1439" alt="screen shot 2017-12-09 at 22 10 37" src="https://user-images.githubusercontent.com/23668432/33796384-316d6854-dd2e-11e7-8566-e6798e77a3b0.png">

**Comment by poofee** [comment]
我觉得这不是规定里的东西 看个人审美 也许发word模板的人只是在word里没有特意设置随便敲了一下页眉就是那样了呢？

**Comment by jiajun-hit** [comment]
哦哦哦，原来是这样，不过觉得这样要比word模板好看很多

**Comment by poofee** [comment]
我觉得左边好看

**Comment by dustincys** [comment]
@jiajun-hit  《规范》没看懂就对了，因为这是窝工规范的[版心歧义](http://yanshuo.name/cn/2017/06/hithesisregulation/)造成的，具体页眉设置方法和理由也在[版心歧义](http://yanshuo.name/cn/2017/06/hithesisregulation/)这篇说明中有提到。

其实，版心歧义、行距设置等等在在read.me中都有提到。如再有其他问题随时提问。

**Comment by jiajun-hit** [comment]
哦哦，看到了，我再仔细研读下。非常感谢解答。
