### ISSUE TITLE
目录中Abstract底部的空隙过大

### ISSUE THREAD

**Issue by hzxie** [dustincys/hithesis#90]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp

**描述bug具体信息** 

窝工在（规范/word模板中）如图：

<img width="1392" alt="Screen Shot 2021-04-09 at 1 13 34 PM" src="https://user-images.githubusercontent.com/1730504/114131571-69117400-9935-11eb-9734-0b31c2e48615.png">

hithesis的格式如图：

<img width="1242" alt="Screen Shot 2021-04-09 at 1 12 39 PM" src="https://user-images.githubusercontent.com/1730504/114131527-5d25b200-9935-11eb-9f26-2f5bb510ab8e.png">

**Comment by dustincys** [comment]
在主文件thesis.tex中有个选项控制这个空白。
