### ISSUE TITLE
参考文献 - 会议 - 格式有误

### ISSUE THREAD

**Issue by ZhaopeiG** [dustincys/hithesis#94]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博士

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/2021/0508/c3425a254066/page.htm

**描述bug具体信息** 

学校在word模板中关于会议类型[C]的引用，其中包含了地址信息，

如图：
![image](https://user-images.githubusercontent.com/3530785/117683860-0c7ccf80-b1e7-11eb-803c-9e66c6caac15.png)

hithesis的格式中，虽然留有地址信息的填写空间，但最终编译出的论文参考文献，并没有地址信息

如图：
![image](https://user-images.githubusercontent.com/3530785/117685413-7ea1e400-b1e8-11eb-816a-f323f6ce2ac5.png)

如码：
![image](https://user-images.githubusercontent.com/3530785/117685486-8feaf080-b1e8-11eb-9258-f378bad11a6a.png)

**Comment by dustincys** [comment]
这个参考文献今年更新到了国标2015，今年是最混乱的，根据通知，今年新旧规定都适用，就是用哪一个版本都可以。
