### ISSUE TITLE
关于公式字体的问题咨询

### ISSUE THREAD

**Issue by MayeZhang** [dustincys/hithesis#98]
请问一下模版里的这种公式字体是规定的格式吗？
![1031622596828_ pic](https://user-images.githubusercontent.com/42532687/120568336-3d4ad000-c446-11eb-93a1-06abadebf462.jpg)

在一些外文期刊论文中看到的公式字体都是这种形式的：
![1051622596884_ pic](https://user-images.githubusercontent.com/42532687/120568407-610e1600-c446-11eb-8903-c24812538478.jpg)

这是因为用的字体包不一样吗？我在LaTexiT中生成的也是第二种格式的，请问这个有什么办法设置成统一的字体吗
![image](https://user-images.githubusercontent.com/42532687/120568533-a3cfee00-c446-11eb-8898-17f2a30258a0.png)

**Comment by dustincys** [comment]
主文件有开关控制。
